import { z } from "zod";
import { createTRPCRouter, organizationProcedure, writerProcedure, adminOrgProcedure } from "../../trpc";
import { TRPCError } from "@trpc/server";
import { DataAssetType, DataSensitivity, DataCategory, LegalBasis, TransferMechanism } from "@prisma/client";
import { hasRopaExportAccess } from "../../services/licensing/entitlement";

// ============================================================
// AUTO-FLOW GENERATION
// ============================================================

/**
 * Rank data assets by their typical position in a data pipeline.
 * Lower rank = closer to the source (where data enters). Higher rank =
 * closer to the sink (where data ends up).
 *
 * This is a heuristic — users can always edit or delete auto-generated flows.
 */
const ASSET_FLOW_RANK: Record<DataAssetType, number> = {
  APPLICATION: 1,   // User-facing app / form / website — data capture
  CLOUD_SERVICE: 2, // Middleware / API / ETL / ingest tier
  DATABASE: 3,      // Primary store
  FILE_SYSTEM: 4,   // Reports / exports / backups
  THIRD_PARTY: 5,   // Downstream vendor / analytics / integration sink
  PHYSICAL: 6,
  OTHER: 4,
};

/**
 * Auto-generate DataFlow records for an activity's linked assets.
 *
 * Sorts the linked assets by ASSET_FLOW_RANK and creates flows between
 * consecutive pairs (chain topology). Dedupes against existing flows in
 * either direction so user-edited graphs aren't clobbered.
 *
 * Returns the number of flows created.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function generateFlowsForActivity(
  tx: any,
  organizationId: string,
  activityId: string
): Promise<number> {
  const activity = await tx.processingActivity.findFirst({
    where: { id: activityId, organizationId },
    include: {
      assets: {
        include: { dataAsset: true },
      },
    },
  });

  if (!activity || activity.assets.length < 2) return 0;

  // Sort by flow rank, then name (deterministic tie-break)
  type LinkedAsset = { dataAsset: { id: string; name: string; type: DataAssetType } };
  const sorted = ([...activity.assets] as LinkedAsset[]).sort((a, b) => {
    const rankA = ASSET_FLOW_RANK[a.dataAsset.type] ?? 4;
    const rankB = ASSET_FLOW_RANK[b.dataAsset.type] ?? 4;
    if (rankA !== rankB) return rankA - rankB;
    return a.dataAsset.name.localeCompare(b.dataAsset.name);
  });

  // Pull existing flows so we can dedupe (in either direction)
  const existingFlows: { sourceAssetId: string; destinationAssetId: string }[] =
    await tx.dataFlow.findMany({
      where: { organizationId },
      select: { sourceAssetId: true, destinationAssetId: true },
    });
  const existingPairs = new Set(
    existingFlows.flatMap((f) => [
      `${f.sourceAssetId}:${f.destinationAssetId}`,
      `${f.destinationAssetId}:${f.sourceAssetId}`,
    ])
  );

  const dataCategories = activity.categories;
  let created = 0;

  for (let i = 0; i < sorted.length - 1; i++) {
    const source = sorted[i]!.dataAsset;
    const dest = sorted[i + 1]!.dataAsset;
    const pairKey = `${source.id}:${dest.id}`;
    if (existingPairs.has(pairKey)) continue;

    await tx.dataFlow.create({
      data: {
        organizationId,
        name: `${activity.name}: ${source.name} -> ${dest.name}`,
        description: `Auto-generated from processing activity "${activity.name}"`,
        sourceAssetId: source.id,
        destinationAssetId: dest.id,
        dataCategories,
        isAutomated: true,
        frequency: "Continuous",
        metadata: { autoGenerated: true, activityId },
      },
    });
    existingPairs.add(pairKey);
    existingPairs.add(`${dest.id}:${source.id}`);
    created++;
  }

  return created;
}

export const dataInventoryRouter = createTRPCRouter({
  // ============================================================
  // DATA ASSETS
  // ============================================================

  // List all data assets
  listAssets: organizationProcedure
    .input(
      z.object({
        organizationId: z.string(),
        type: z.nativeEnum(DataAssetType).optional(),
        search: z.string().optional(),
        limit: z.number().min(1).max(500).default(50),
        cursor: z.string().optional(),
      })
    )
    .query(async ({ ctx, input }) => {
      const assets = await ctx.prisma.dataAsset.findMany({
        where: {
          organizationId: ctx.organization.id,
          type: input.type,
          ...(input.search && {
            OR: [
              { name: { contains: input.search, mode: "insensitive" } },
              { description: { contains: input.search, mode: "insensitive" } },
            ],
          }),
        },
        include: {
          dataElements: {
            orderBy: { name: "asc" as const },
          },
          _count: {
            select: {
              dataElements: true,
              processingActivityAssets: true,
            },
          },
        },
        orderBy: { name: "asc" },
        take: input.limit + 1,
        cursor: input.cursor ? { id: input.cursor } : undefined,
      });

      let nextCursor: string | undefined;
      if (assets.length > input.limit) {
        const nextItem = assets.pop();
        nextCursor = nextItem?.id;
      }

      return { assets, nextCursor };
    }),

  // Get a single data asset
  getAsset: organizationProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .query(async ({ ctx, input }) => {
      const asset = await ctx.prisma.dataAsset.findFirst({
        where: {
          id: input.id,
          organizationId: ctx.organization.id,
        },
        include: {
          dataElements: {
            orderBy: { name: "asc" },
          },
          processingActivityAssets: {
            include: {
              processingActivity: true,
              linkedElements: {
                include: { dataElement: true },
              },
            },
          },
          sourceFlows: {
            include: {
              destinationAsset: true,
            },
          },
          destFlows: {
            include: {
              sourceAsset: true,
            },
          },
        },
      });

      if (!asset) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data asset not found",
        });
      }

      return asset;
    }),

  // Create a data asset
  createAsset: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        name: z.string().min(1).max(200),
        description: z.string().optional(),
        type: z.nativeEnum(DataAssetType),
        owner: z.string().optional(),
        location: z.string().optional(),
        hostingType: z.string().optional(),
        vendor: z.string().optional(),
        isProduction: z.boolean().default(true),
        metadata: z.record(z.string(), z.any()).optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const asset = await ctx.prisma.dataAsset.create({
        data: {
          organizationId: ctx.organization.id,
          name: input.name,
          description: input.description,
          type: input.type,
          owner: input.owner,
          location: input.location,
          hostingType: input.hostingType,
          vendor: input.vendor,
          isProduction: input.isProduction,
          metadata: input.metadata,
        },
      });

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataAsset",
          entityId: asset.id,
          action: "CREATE",
          changes: input,
        },
      });

      return asset;
    }),

  // Update a data asset
  updateAsset: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        id: z.string(),
        name: z.string().min(1).max(200).optional(),
        description: z.string().optional().nullable(),
        type: z.nativeEnum(DataAssetType).optional(),
        owner: z.string().optional().nullable(),
        location: z.string().optional().nullable(),
        hostingType: z.string().optional().nullable(),
        vendor: z.string().optional().nullable(),
        isProduction: z.boolean().optional(),
        metadata: z.record(z.string(), z.any()).optional().nullable(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, organizationId, metadata, ...restData } = input;

      const asset = await ctx.prisma.dataAsset.updateMany({
        where: { id, organizationId: ctx.organization.id },
        data: {
          ...restData,
          ...(metadata !== undefined && { metadata: metadata ?? undefined }),
        },
      });

      if (asset.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data asset not found",
        });
      }

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataAsset",
          entityId: id,
          action: "UPDATE",
          changes: { ...restData, metadata },
        },
      });

      // Security: Return with org check to prevent data leak
      return ctx.prisma.dataAsset.findFirst({
        where: { id, organizationId: ctx.organization.id },
      });
    }),

  // Delete a data asset
  deleteAsset: adminOrgProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const asset = await ctx.prisma.dataAsset.deleteMany({
        where: { id: input.id, organizationId: ctx.organization.id },
      });

      if (asset.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data asset not found",
        });
      }

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataAsset",
          entityId: input.id,
          action: "DELETE",
        },
      });

      return { success: true };
    }),

  // ============================================================
  // DATA ELEMENTS
  // ============================================================

  // Get a single data element with parent asset and linked activities
  getElement: organizationProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .query(async ({ ctx, input }) => {
      const element = await ctx.prisma.dataElement.findFirst({
        where: { id: input.id, organizationId: ctx.organization.id },
        include: {
          dataAsset: {
            select: { id: true, name: true, type: true, vendor: true },
          },
          activityAssetLinks: {
            include: {
              processingActivityAsset: {
                include: {
                  processingActivity: {
                    select: {
                      id: true,
                      name: true,
                      purpose: true,
                      legalBasis: true,
                      isActive: true,
                    },
                  },
                },
              },
            },
          },
        },
      });

      if (!element) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data element not found",
        });
      }

      const linkedActivities = element.activityAssetLinks.map((link) => ({
        linkId: link.id,
        activity: link.processingActivityAsset.processingActivity,
      }));

      return {
        id: element.id,
        name: element.name,
        description: element.description,
        category: element.category,
        sensitivity: element.sensitivity,
        isPersonalData: element.isPersonalData,
        isSpecialCategory: element.isSpecialCategory,
        retentionDays: element.retentionDays,
        legalBasis: element.legalBasis,
        createdAt: element.createdAt,
        updatedAt: element.updatedAt,
        dataAsset: element.dataAsset,
        linkedActivities,
      };
    }),

  // Add data element to asset
  addElement: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        dataAssetId: z.string(),
        name: z.string().min(1).max(200),
        description: z.string().optional(),
        category: z.nativeEnum(DataCategory),
        sensitivity: z.nativeEnum(DataSensitivity).default(DataSensitivity.INTERNAL),
        isPersonalData: z.boolean().default(true),
        isSpecialCategory: z.boolean().default(false),
        retentionDays: z.number().optional(),
        legalBasis: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      // Verify asset belongs to org
      const asset = await ctx.prisma.dataAsset.findFirst({
        where: { id: input.dataAssetId, organizationId: ctx.organization.id },
      });

      if (!asset) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data asset not found",
        });
      }

      const element = await ctx.prisma.dataElement.create({
        data: {
          organizationId: ctx.organization.id,
          dataAssetId: input.dataAssetId,
          name: input.name,
          description: input.description,
          category: input.category,
          sensitivity: input.sensitivity,
          isPersonalData: input.isPersonalData,
          isSpecialCategory: input.isSpecialCategory,
          retentionDays: input.retentionDays,
          legalBasis: input.legalBasis,
        },
      });

      return element;
    }),

  // Update data element
  updateElement: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        id: z.string(),
        name: z.string().min(1).max(200).optional(),
        description: z.string().optional().nullable(),
        category: z.nativeEnum(DataCategory).optional(),
        sensitivity: z.nativeEnum(DataSensitivity).optional(),
        isPersonalData: z.boolean().optional(),
        isSpecialCategory: z.boolean().optional(),
        retentionDays: z.number().optional().nullable(),
        legalBasis: z.string().optional().nullable(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, organizationId, ...data } = input;

      const element = await ctx.prisma.dataElement.updateMany({
        where: { id, organizationId: ctx.organization.id },
        data,
      });

      if (element.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data element not found",
        });
      }

      // Security: Return with org check to prevent data leak
      return ctx.prisma.dataElement.findFirst({
        where: { id, organizationId: ctx.organization.id },
      });
    }),

  // Delete data element
  deleteElement: adminOrgProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const element = await ctx.prisma.dataElement.deleteMany({
        where: { id: input.id, organizationId: ctx.organization.id },
      });

      if (element.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data element not found",
        });
      }

      return { success: true };
    }),

  // ============================================================
  // PROCESSING ACTIVITIES (ROPA)
  // ============================================================

  // List processing activities
  listActivities: organizationProcedure
    .input(
      z.object({
        organizationId: z.string(),
        isActive: z.boolean().optional(),
        search: z.string().optional(),
        limit: z.number().min(1).max(500).default(50),
        cursor: z.string().optional(),
      })
    )
    .query(async ({ ctx, input }) => {
      const activities = await ctx.prisma.processingActivity.findMany({
        where: {
          organizationId: ctx.organization.id,
          isActive: input.isActive,
          ...(input.search && {
            OR: [
              { name: { contains: input.search, mode: "insensitive" } },
              { purpose: { contains: input.search, mode: "insensitive" } },
            ],
          }),
        },
        include: {
          assets: {
            include: {
              dataAsset: true,
            },
          },
          _count: {
            select: {
              transfers: true,
              assessments: true,
            },
          },
        },
        orderBy: { name: "asc" },
        take: input.limit + 1,
        cursor: input.cursor ? { id: input.cursor } : undefined,
      });

      let nextCursor: string | undefined;
      if (activities.length > input.limit) {
        const nextItem = activities.pop();
        nextCursor = nextItem?.id;
      }

      return { activities, nextCursor };
    }),

  // Get a single processing activity
  getActivity: organizationProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .query(async ({ ctx, input }) => {
      const activity = await ctx.prisma.processingActivity.findFirst({
        where: {
          id: input.id,
          organizationId: ctx.organization.id,
        },
        include: {
          assets: {
            include: {
              linkedElements: {
                include: { dataElement: true },
              },
              dataAsset: {
                include: {
                  dataElements: true,
                },
              },
            },
          },
          transfers: {
            include: {
              jurisdiction: true,
            },
          },
          assessments: true,
        },
      });

      if (!activity) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Processing activity not found",
        });
      }

      return activity;
    }),

  // Create a processing activity
  createActivity: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        name: z.string().min(1).max(200),
        description: z.string().optional(),
        purpose: z.string().min(1),
        legalBasis: z.nativeEnum(LegalBasis),
        legalBasisDetail: z.string().optional(),
        dataSubjects: z.array(z.string()),
        categories: z.array(z.nativeEnum(DataCategory)),
        recipients: z.array(z.string()).default([]),
        retentionPeriod: z.string().optional(),
        retentionDays: z.number().optional(),
        automatedDecisionMaking: z.boolean().default(false),
        automatedDecisionDetail: z.string().optional(),
        assetIds: z.array(z.string()).default([]),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { assetIds, organizationId: _orgId, ...data } = input;

      const activity = await ctx.prisma.processingActivity.create({
        data: {
          organizationId: ctx.organization.id,
          ...data,
          assets: {
            create: assetIds.map((assetId) => ({
              dataAssetId: assetId,
            })),
          },
        },
        include: {
          assets: {
            include: {
              dataAsset: true,
            },
          },
        },
      });

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "ProcessingActivity",
          entityId: activity.id,
          action: "CREATE",
          changes: input,
        },
      });

      return activity;
    }),

  // Update a processing activity
  updateActivity: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        id: z.string(),
        name: z.string().min(1).max(200).optional(),
        description: z.string().optional().nullable(),
        purpose: z.string().optional(),
        legalBasis: z.nativeEnum(LegalBasis).optional(),
        legalBasisDetail: z.string().optional().nullable(),
        dataSubjects: z.array(z.string()).optional(),
        categories: z.array(z.nativeEnum(DataCategory)).optional(),
        recipients: z.array(z.string()).optional(),
        retentionPeriod: z.string().optional().nullable(),
        retentionDays: z.number().optional().nullable(),
        automatedDecisionMaking: z.boolean().optional(),
        automatedDecisionDetail: z.string().optional().nullable(),
        isActive: z.boolean().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, organizationId, ...data } = input;

      const activity = await ctx.prisma.processingActivity.updateMany({
        where: { id, organizationId: ctx.organization.id },
        data,
      });

      if (activity.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Processing activity not found",
        });
      }

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "ProcessingActivity",
          entityId: id,
          action: "UPDATE",
          changes: data,
        },
      });

      // Security: Return with org check to prevent data leak
      return ctx.prisma.processingActivity.findFirst({
        where: { id, organizationId: ctx.organization.id },
      });
    }),

  // Link assets to activity (with optional element-level granularity)
  linkAssets: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        activityId: z.string(),
        assets: z.array(
          z.object({
            assetId: z.string(),
            elementIds: z.array(z.string()).optional(),
          })
        ),
      })
    )
    .mutation(async ({ ctx, input }) => {
      // Verify activity belongs to org
      const activity = await ctx.prisma.processingActivity.findFirst({
        where: { id: input.activityId, organizationId: ctx.organization.id },
      });

      if (!activity) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Processing activity not found",
        });
      }

      // Remove existing links (cascade deletes element links)
      await ctx.prisma.processingActivityAsset.deleteMany({
        where: { processingActivityId: input.activityId },
      });

      // Create asset links with optional element-level specificity
      for (const { assetId, elementIds } of input.assets) {
        const paAsset = await ctx.prisma.processingActivityAsset.create({
          data: {
            processingActivityId: input.activityId,
            dataAssetId: assetId,
          },
        });

        if (elementIds && elementIds.length > 0) {
          await ctx.prisma.processingActivityAssetElement.createMany({
            data: elementIds.map((dataElementId) => ({
              processingActivityAssetId: paAsset.id,
              dataElementId,
            })),
          });
        }
      }

      const flowsCreated = await generateFlowsForActivity(
        ctx.prisma,
        ctx.organization.id,
        input.activityId
      );

      return { success: true, flowsCreated };
    }),

  // Link processing activities to a data asset (with optional element-level granularity)
  linkActivitiesToAsset: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        assetId: z.string(),
        activities: z.array(
          z.object({
            activityId: z.string(),
            elementIds: z.array(z.string()).optional(),
          })
        ),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const asset = await ctx.prisma.dataAsset.findFirst({
        where: { id: input.assetId, organizationId: ctx.organization.id },
      });

      if (!asset) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data asset not found",
        });
      }

      // Remove existing links for this asset (cascade deletes element links)
      await ctx.prisma.processingActivityAsset.deleteMany({
        where: { dataAssetId: input.assetId },
      });

      // Create activity links with optional element-level specificity
      for (const { activityId, elementIds } of input.activities) {
        const paAsset = await ctx.prisma.processingActivityAsset.create({
          data: {
            processingActivityId: activityId,
            dataAssetId: input.assetId,
          },
        });

        if (elementIds && elementIds.length > 0) {
          await ctx.prisma.processingActivityAssetElement.createMany({
            data: elementIds.map((dataElementId) => ({
              processingActivityAssetId: paAsset.id,
              dataElementId,
            })),
          });
        }
      }

      // Regenerate flows for every affected activity
      let flowsCreated = 0;
      for (const { activityId } of input.activities) {
        flowsCreated += await generateFlowsForActivity(
          ctx.prisma,
          ctx.organization.id,
          activityId
        );
      }

      return { success: true, flowsCreated };
    }),

  // Manually trigger flow generation for an activity (useful for
  // existing activities where flows weren't auto-generated at link time,
  // or when the user wants to regenerate after editing assets).
  regenerateFlows: writerProcedure
    .input(z.object({ organizationId: z.string(), activityId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const flowsCreated = await generateFlowsForActivity(
        ctx.prisma,
        ctx.organization.id,
        input.activityId
      );
      return { flowsCreated };
    }),

  // Regenerate flows for all activities in the org
  regenerateAllFlows: writerProcedure
    .input(z.object({ organizationId: z.string() }))
    .mutation(async ({ ctx }) => {
      const activities = await ctx.prisma.processingActivity.findMany({
        where: { organizationId: ctx.organization.id },
        select: { id: true },
      });
      let flowsCreated = 0;
      for (const a of activities) {
        flowsCreated += await generateFlowsForActivity(
          ctx.prisma,
          ctx.organization.id,
          a.id
        );
      }
      return { flowsCreated, activitiesProcessed: activities.length };
    }),

  // ============================================================
  // DATA FLOWS
  // ============================================================

  // List data flows
  listFlows: organizationProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ ctx }) => {
      return ctx.prisma.dataFlow.findMany({
        where: { organizationId: ctx.organization.id },
        include: {
          sourceAsset: true,
          destinationAsset: true,
        },
        orderBy: { name: "asc" },
      });
    }),

  // Get a single data flow
  getFlow: organizationProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .query(async ({ ctx, input }) => {
      const flow = await ctx.prisma.dataFlow.findFirst({
        where: {
          id: input.id,
          organizationId: ctx.organization.id,
        },
        include: {
          sourceAsset: true,
          destinationAsset: true,
        },
      });

      if (!flow) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data flow not found",
        });
      }

      return flow;
    }),

  // Create data flow
  createFlow: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        name: z.string().min(1).max(200),
        description: z.string().optional(),
        sourceAssetId: z.string(),
        destinationAssetId: z.string(),
        dataCategories: z.array(z.nativeEnum(DataCategory)),
        frequency: z.string().optional(),
        volume: z.string().optional(),
        encryptionMethod: z.string().optional(),
        isAutomated: z.boolean().default(true),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const flow = await ctx.prisma.dataFlow.create({
        data: {
          organizationId: ctx.organization.id,
          name: input.name,
          description: input.description,
          sourceAssetId: input.sourceAssetId,
          destinationAssetId: input.destinationAssetId,
          dataCategories: input.dataCategories,
          frequency: input.frequency,
          volume: input.volume,
          encryptionMethod: input.encryptionMethod,
          isAutomated: input.isAutomated,
        },
        include: {
          sourceAsset: true,
          destinationAsset: true,
        },
      });

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataFlow",
          entityId: flow.id,
          action: "CREATE",
          changes: input,
        },
      });

      return flow;
    }),

  // Update data flow
  updateFlow: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        id: z.string(),
        name: z.string().min(1).max(200).optional(),
        description: z.string().optional().nullable(),
        sourceAssetId: z.string().optional(),
        destinationAssetId: z.string().optional(),
        dataCategories: z.array(z.nativeEnum(DataCategory)).optional(),
        frequency: z.string().optional().nullable(),
        volume: z.string().optional().nullable(),
        encryptionMethod: z.string().optional().nullable(),
        isAutomated: z.boolean().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, organizationId, ...data } = input;

      const flow = await ctx.prisma.dataFlow.updateMany({
        where: { id, organizationId: ctx.organization.id },
        data,
      });

      if (flow.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data flow not found",
        });
      }

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataFlow",
          entityId: id,
          action: "UPDATE",
          changes: data,
        },
      });

      return ctx.prisma.dataFlow.findFirst({
        where: { id, organizationId: ctx.organization.id },
        include: {
          sourceAsset: true,
          destinationAsset: true,
        },
      });
    }),

  // Delete data flow
  deleteFlow: adminOrgProcedure
    .input(z.object({ organizationId: z.string(), id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const flow = await ctx.prisma.dataFlow.deleteMany({
        where: { id: input.id, organizationId: ctx.organization.id },
      });

      if (flow.count === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data flow not found",
        });
      }

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataFlow",
          entityId: input.id,
          action: "DELETE",
        },
      });

      return { success: true };
    }),

  // ============================================================
  // DATA TRANSFERS
  // ============================================================

  // List data transfers
  listTransfers: organizationProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ ctx }) => {
      return ctx.prisma.dataTransfer.findMany({
        where: { organizationId: ctx.organization.id },
        include: {
          processingActivity: true,
          jurisdiction: true,
          assessments: {
            select: { id: true, status: true, riskLevel: true, completedAt: true },
            orderBy: { createdAt: "desc" },
            take: 1,
          },
        },
        orderBy: { name: "asc" },
      });
    }),

  // Create data transfer
  createTransfer: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        processingActivityId: z.string().optional(),
        name: z.string().min(1).max(200),
        description: z.string().optional(),
        destinationCountry: z.string(),
        destinationOrg: z.string().optional(),
        jurisdictionId: z.string().optional(),
        mechanism: z.nativeEnum(TransferMechanism),
        safeguards: z.string().optional(),
        documentUrl: z.string().optional(),
        tiaCompleted: z.boolean().default(false),
        tiaDate: z.date().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const transfer = await ctx.prisma.dataTransfer.create({
        data: {
          organizationId: ctx.organization.id,
          processingActivityId: input.processingActivityId,
          name: input.name,
          description: input.description,
          destinationCountry: input.destinationCountry,
          destinationOrg: input.destinationOrg,
          jurisdictionId: input.jurisdictionId,
          mechanism: input.mechanism,
          safeguards: input.safeguards,
          documentUrl: input.documentUrl,
          tiaCompleted: input.tiaCompleted,
          tiaDate: input.tiaDate,
        },
        include: {
          processingActivity: true,
          jurisdiction: true,
        },
      });

      return transfer;
    }),

  // ============================================================
  // TRANSFER COMPLIANCE (Feature 4)
  // ============================================================

  // Get transfer compliance stats
  getTransferStats: organizationProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ ctx }) => {
      const transfers = await ctx.prisma.dataTransfer.findMany({
        where: { organizationId: ctx.organization.id, isActive: true },
        select: {
          id: true,
          destinationCountry: true,
          mechanism: true,
          complianceStatus: true,
          sccExpiryDate: true,
          tiaCompleted: true,
        },
      });

      const total = transfers.length;
      const compliant = transfers.filter((t) => t.complianceStatus === "COMPLIANT").length;
      const needsReview = transfers.filter((t) => t.complianceStatus === "NEEDS_REVIEW").length;
      const nonCompliant = transfers.filter((t) => t.complianceStatus === "NON_COMPLIANT").length;
      const pending = transfers.filter((t) => !t.complianceStatus || t.complianceStatus === "PENDING").length;
      const withoutTia = transfers.filter((t) => !t.tiaCompleted && t.mechanism === "STANDARD_CONTRACTUAL_CLAUSES").length;

      const now = new Date();
      const thirtyDays = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
      const expiringSoon = transfers.filter(
        (t) => t.sccExpiryDate && t.sccExpiryDate > now && t.sccExpiryDate <= thirtyDays
      ).length;

      const countries = [...new Set(transfers.map((t) => t.destinationCountry))];

      return {
        total,
        compliant,
        needsReview,
        nonCompliant,
        pending,
        withoutTia,
        expiringSoon,
        destinationCountries: countries,
      };
    }),

  // Update transfer compliance details
  updateTransferCompliance: writerProcedure
    .input(
      z.object({
        organizationId: z.string(),
        id: z.string(),
        complianceStatus: z.enum(["COMPLIANT", "NEEDS_REVIEW", "NON_COMPLIANT", "PENDING"]).optional(),
        sccExpiryDate: z.date().optional().nullable(),
        supplementaryMeasures: z.any().optional(),
        tiaCompleted: z.boolean().optional(),
        tiaDate: z.date().optional().nullable(),
        safeguards: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, organizationId, ...data } = input;

      const transfer = await ctx.prisma.dataTransfer.findFirst({
        where: { id, organizationId: ctx.organization.id },
      });

      if (!transfer) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data transfer not found",
        });
      }

      const updated = await ctx.prisma.dataTransfer.update({
        where: { id },
        data,
        include: {
          processingActivity: true,
          jurisdiction: true,
        },
      });

      await ctx.prisma.auditLog.create({
        data: {
          organizationId: ctx.organization.id,
          userId: ctx.session.user.id,
          entityType: "DataTransfer",
          entityId: id,
          action: "UPDATE_COMPLIANCE",
          changes: data,
        },
      });

      return updated;
    }),

  // Get Schrems II compliance checklist for a transfer
  getTransferComplianceChecklist: organizationProcedure
    .input(z.object({ organizationId: z.string(), transferId: z.string() }))
    .query(async ({ ctx, input }) => {
      const transfer = await ctx.prisma.dataTransfer.findFirst({
        where: { id: input.transferId, organizationId: ctx.organization.id },
        include: {
          processingActivity: true,
          jurisdiction: true,
        },
      });

      if (!transfer) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Data transfer not found",
        });
      }

      const {
        SCHREMS_II_CHECKLIST,
        SUPPLEMENTARY_MEASURES,
        ADEQUACY_DECISIONS,
        isAdequateCountry,
        getTransferComplianceStatus,
      } = await import("@/config/transfer-compliance-rules");

      const isAdequate = isAdequateCountry(transfer.destinationCountry);
      const adequacyDecision = ADEQUACY_DECISIONS.find(
        (d) => d.countryCode.toUpperCase() === transfer.destinationCountry.toUpperCase()
      );

      const autoStatus = getTransferComplianceStatus({
        mechanism: transfer.mechanism,
        destinationCountry: transfer.destinationCountry,
        tiaCompleted: transfer.tiaCompleted,
        sccExpiryDate: transfer.sccExpiryDate,
        supplementaryMeasures: transfer.supplementaryMeasures as Record<string, unknown> | undefined,
      });

      // Adequate countries don't need the Schrems II / supplementary measures
      // checklists — the adequacy decision covers everything. Return empty
      // arrays in that case so the UI doesn't render irrelevant items.
      const checklist = isAdequate ? [] : SCHREMS_II_CHECKLIST;
      const supplementaryMeasuresList = isAdequate ? [] : SUPPLEMENTARY_MEASURES;

      return {
        transfer: {
          id: transfer.id,
          name: transfer.name,
          destinationCountry: transfer.destinationCountry,
          destinationOrg: transfer.destinationOrg,
          mechanism: transfer.mechanism,
          complianceStatus: transfer.complianceStatus ?? autoStatus,
          suggestedStatus: autoStatus,
          sccExpiryDate: transfer.sccExpiryDate,
          tiaCompleted: transfer.tiaCompleted,
          supplementaryMeasures: transfer.supplementaryMeasures,
        },
        isAdequateCountry: isAdequate,
        adequacyDecision,
        checklist,
        supplementaryMeasures: supplementaryMeasuresList,
      };
    }),

  // ============================================================
  // ROPA EXPORT
  // ============================================================

  // Check if organization has ROPA export access
  hasRopaExportAccess: organizationProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ ctx }) => {
      const hasAccess = await hasRopaExportAccess(ctx.organization.id);
      return { hasAccess };
    }),

  // Export ROPA data
  exportROPA: organizationProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ ctx }) => {
      // Premium feature guard
      const hasAccess = await hasRopaExportAccess(ctx.organization.id);
      if (!hasAccess) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "ROPA Export requires a premium subscription. Enable this add-on to export your Record of Processing Activities.",
        });
      }

      const activities = await ctx.prisma.processingActivity.findMany({
        where: {
          organizationId: ctx.organization.id,
          isActive: true,
        },
        include: {
          assets: {
            include: {
              dataAsset: {
                include: {
                  dataElements: true,
                },
              },
            },
          },
          transfers: {
            include: {
              jurisdiction: true,
            },
          },
        },
        orderBy: { name: "asc" },
      });

      // Format for ROPA export
      return activities.map((activity) => ({
        name: activity.name,
        description: activity.description,
        purpose: activity.purpose,
        legalBasis: activity.legalBasis,
        legalBasisDetail: activity.legalBasisDetail,
        dataSubjects: activity.dataSubjects,
        dataCategories: activity.categories,
        recipients: activity.recipients,
        retentionPeriod: activity.retentionPeriod,
        automatedDecisionMaking: activity.automatedDecisionMaking,
        automatedDecisionDetail: activity.automatedDecisionDetail,
        systems: activity.assets.map((a) => ({
          name: a.dataAsset.name,
          type: a.dataAsset.type,
          location: a.dataAsset.location,
          elements: a.dataAsset.dataElements.map((e) => ({
            name: e.name,
            category: e.category,
            sensitivity: e.sensitivity,
          })),
        })),
        transfers: activity.transfers.map((t) => ({
          destination: t.destinationCountry,
          organization: t.destinationOrg,
          mechanism: t.mechanism,
          safeguards: t.safeguards,
        })),
        lastReviewed: activity.lastReviewedAt,
        nextReview: activity.nextReviewAt,
      }));
    }),
});
