import type { SuiteSecrets } from './secrets'

/** The version (image tag) written on first run; `update` pulls whatever it names. */
export const DEFAULT_VERSION = 'latest'

/** Minimal KEY=VALUE parser for tests/round-trips (ignores comments + blanks). */
export function parseEnv(text: string): Record<string, string> {
	const out: Record<string, string> = {}
	for (const raw of text.split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const eq = line.indexOf('=')
		if (eq === -1) continue
		out[line.slice(0, eq)] = line.slice(eq + 1)
	}
	return out
}

/** Read one value out of .env text without evaluating it (suite.sh env_value). */
export function envValue(text: string, key: string): string | null {
	for (const raw of text.split('\n')) {
		if (raw.startsWith(`${key}=`)) return raw.slice(key.length + 1)
	}
	return null
}

/**
 * Render the .env docker-compose.yml expects, mirroring suite.sh ensure_env's heredoc:
 * same keys, same comments (adapted attribution), same order. Values are minted secrets
 * and a version tag — never free text that needs quoting — so plain KEY=VALUE is safe.
 * The file is generated ONCE and NEVER overwritten (store.ts keeps an existing .env,
 * adopting a CLI-kit install); new random passwords would not open the old databases.
 */
export function renderEnv(
	secrets: SuiteSecrets,
	version: string = DEFAULT_VERSION,
	generatedAt: string = new Date().toISOString().slice(0, 16).replace('T', ' ')
): string {
	return [
		`# todo.law suite: settings generated by TODO.LAW Suite (desktop) on ${generatedAt}.`,
		'# Keep this file: it holds the keys to your local databases and backups.',
		'# To move to another computer, copy this file across BEFORE starting the suite.',
		'',
		'# Which release to run. "latest" always pulls the newest published images;',
		'# pin a version (e.g. v0.1.1) for a reproducible install.',
		`TODOLAW_VERSION=${version}`,
		'',
		'# Database passwords (used only inside this stack).',
		`DPO_DB_PASSWORD=${secrets.DPO_DB_PASSWORD}`,
		`DEAL_DB_PASSWORD=${secrets.DEAL_DB_PASSWORD}`,
		`AIS_DB_PASSWORD=${secrets.AIS_DB_PASSWORD}`,
		'',
		'# Session signing secret shared by the apps.',
		`NEXTAUTH_SECRET=${secrets.NEXTAUTH_SECRET}`,
		'',
		'# Cross-app bridge: the SAME key on DPO Central + AI Sentinel turns on the',
		'# unified DPIA + AI-Act view between them. Generated here so it works out of',
		'# the box; blank it out if you want the two apps fully independent.',
		`BRIDGE_API_KEY=${secrets.BRIDGE_API_KEY}`,
		'',
		'# Encrypts backup files. You need this exact value to restore on another',
		'# computer. Keep a copy somewhere safe (e.g. your password manager).',
		`BACKUP_PASSPHRASE=${secrets.BACKUP_PASSPHRASE}`,
		'',
		'# Asked once per browser before anyone can sign in to the apps. A speed bump',
		'# against casual snooping on this computer; the real protection is the',
		'# machine\'s own login + disk encryption. Blank = no gate.',
		`WORKSPACE_PASSPHRASE=${secrets.WORKSPACE_PASSPHRASE}`,
		''
	].join('\n')
}
