"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  type NodeMouseHandler,
  Panel,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { AssetNode } from "@/components/privacy/data-flow/AssetNode";
import { FlowEdge } from "@/components/privacy/data-flow/FlowEdge";
import {
  FlowFilterToolbar,
  DEFAULT_FILTERS,
  type FlowFilters,
} from "@/components/privacy/data-flow/FlowFilterToolbar";
import { classifyCategories } from "@/components/privacy/data-flow/flow-palette";
import {
  useDataFlowGraph,
  type AssetData,
  type FlowData,
  type AssetNode as AssetNodeType,
  type FlowEdge as FlowEdgeType,
} from "@/components/privacy/data-flow/useDataFlowGraph";

const nodeTypes = { assetNode: AssetNode };
const edgeTypes = { flowEdge: FlowEdge };

// ── Mock data ────────────────────────────────────────────────────────────────
const MOCK_ASSETS: AssetData[] = [
  { id: "crm",      name: "Customer CRM",         type: "APPLICATION",   owner: "Sales Ops",      location: "AWS eu-west-1",   hostingType: "Cloud",     vendor: "HubSpot",  isProduction: true,  description: null },
  { id: "web",      name: "Marketing Website",    type: "APPLICATION",   owner: "Marketing",      location: "Vercel Frankfurt",hostingType: "Cloud",     vendor: null,       isProduction: true,  description: null },
  { id: "dw",       name: "Analytics Warehouse",  type: "DATABASE",      owner: "Data Team",      location: "Snowflake EU",    hostingType: "Cloud",     vendor: "Snowflake",isProduction: true,  description: null },
  { id: "userdb",   name: "User Database",        type: "DATABASE",      owner: "Engineering",    location: "AWS eu-west-1",   hostingType: "Cloud",     vendor: null,       isProduction: true,  description: null },
  { id: "clinical", name: "Clinical Records",     type: "APPLICATION",   owner: "Clinical IT",    location: "AWS Ireland",     hostingType: "Cloud",     vendor: null,       isProduction: true,  description: null },
  { id: "stripe",   name: "Stripe Payments",      type: "THIRD_PARTY",   owner: "Finance",        location: "US + EU",         hostingType: "SaaS",      vendor: "Stripe",   isProduction: true,  description: null },
  { id: "mail",     name: "Marketing Platform",   type: "CLOUD_SERVICE", owner: "Marketing",      location: "Klaviyo US",      hostingType: "SaaS",      vendor: "Klaviyo",  isProduction: true,  description: null },
  { id: "archive",  name: "Legal Archive",        type: "FILE_SYSTEM",   owner: "Legal",          location: "Azure NL",        hostingType: "Cloud",     vendor: null,       isProduction: false, description: null },
];

const mockAsset = (id: string) => MOCK_ASSETS.find((a) => a.id === id)!;

const MOCK_FLOWS: FlowData[] = [
  {
    id: "f1", name: "Lead capture", description: null,
    sourceAssetId: "web", destinationAssetId: "crm",
    dataCategories: ["IDENTIFIERS", "BEHAVIORAL"],
    frequency: "Continuous", volume: "5k events/day",
    encryptionMethod: "TLS 1.3", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("web"), destinationAsset: mockAsset("crm"),
  },
  {
    id: "f2", name: "CRM sync to warehouse", description: null,
    sourceAssetId: "crm", destinationAssetId: "dw",
    dataCategories: ["IDENTIFIERS", "DEMOGRAPHICS", "BEHAVIORAL"],
    frequency: "Daily", volume: "2GB/day",
    encryptionMethod: "TLS 1.2", isAutomated: true,
    metadata: { autoGenerated: true }, sourceAsset: mockAsset("crm"), destinationAsset: mockAsset("dw"),
  },
  {
    id: "f3", name: "User registration", description: null,
    sourceAssetId: "web", destinationAssetId: "userdb",
    dataCategories: ["IDENTIFIERS"],
    frequency: "Continuous", volume: "200 events/hour",
    encryptionMethod: "TLS 1.3", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("web"), destinationAsset: mockAsset("userdb"),
  },
  {
    id: "f4", name: "Payment capture", description: null,
    sourceAssetId: "crm", destinationAssetId: "stripe",
    dataCategories: ["IDENTIFIERS", "FINANCIAL"],
    frequency: "Hourly", volume: "150 tx/hour",
    encryptionMethod: "TLS 1.3 + E2E", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("crm"), destinationAsset: mockAsset("stripe"),
  },
  {
    id: "f5", name: "Clinical intake", description: null,
    sourceAssetId: "crm", destinationAssetId: "clinical",
    dataCategories: ["IDENTIFIERS", "HEALTH"],
    frequency: "Daily", volume: "30 records/day",
    encryptionMethod: "TLS 1.3 + AES-256", isAutomated: false,
    metadata: null, sourceAsset: mockAsset("crm"), destinationAsset: mockAsset("clinical"),
  },
  {
    id: "f6", name: "Clinical biometrics", description: null,
    sourceAssetId: "clinical", destinationAssetId: "dw",
    dataCategories: ["HEALTH", "BIOMETRIC"],
    frequency: "Weekly", volume: "500MB/week",
    encryptionMethod: "TLS 1.3 + AES-256", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("clinical"), destinationAsset: mockAsset("dw"),
  },
  {
    id: "f7", name: "Email marketing segments", description: null,
    sourceAssetId: "dw", destinationAssetId: "mail",
    dataCategories: ["IDENTIFIERS", "BEHAVIORAL", "DEMOGRAPHICS"],
    frequency: "Daily", volume: "all subscribers",
    encryptionMethod: "TLS 1.3", isAutomated: true,
    metadata: { autoGenerated: true }, sourceAsset: mockAsset("dw"), destinationAsset: mockAsset("mail"),
  },
  {
    id: "f8", name: "Opt-out sync", description: null,
    sourceAssetId: "mail", destinationAssetId: "crm",
    dataCategories: ["IDENTIFIERS"],
    frequency: "Daily", volume: "varies",
    encryptionMethod: "TLS 1.3", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("mail"), destinationAsset: mockAsset("crm"),
  },
  {
    id: "f9", name: "Legal retention export", description: null,
    sourceAssetId: "userdb", destinationAssetId: "archive",
    dataCategories: ["IDENTIFIERS", "FINANCIAL", "EMPLOYMENT"],
    frequency: "Monthly", volume: "10GB/month",
    encryptionMethod: "TLS 1.3 + AES-256", isAutomated: false,
    metadata: null, sourceAsset: mockAsset("userdb"), destinationAsset: mockAsset("archive"),
  },
  {
    id: "f10", name: "Payment reconciliation", description: null,
    sourceAssetId: "stripe", destinationAssetId: "dw",
    dataCategories: ["FINANCIAL"],
    frequency: "Daily", volume: "150 records/day",
    encryptionMethod: "TLS 1.3", isAutomated: true,
    metadata: null, sourceAsset: mockAsset("stripe"), destinationAsset: mockAsset("dw"),
  },
];

export function PreviewCanvas() {
  const { nodes: graphNodes, edges: graphEdges, isLoading } = useDataFlowGraph({
    mode: "all",
    assets: MOCK_ASSETS,
    flows: MOCK_FLOWS,
  });

  const [nodes, setNodes, onNodesChange] = useNodesState<AssetNodeType>(graphNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState<FlowEdgeType>(graphEdges);

  const [filters, setFilters] = useState<FlowFilters>(DEFAULT_FILTERS);
  const [focusedNodeId, setFocusedNodeId] = useState<string | null>(null);

  const { displayNodes, displayEdges, visibleEdgeCount } = useMemo(() => {
    const edgePasses = (e: FlowEdgeType): boolean => {
      const flow = e.data?.flow;
      if (!flow) return false;
      if (!filters.showAutoGenerated && e.data?.isAutoGenerated) return false;
      if (filters.sensitivity !== "all") {
        if (classifyCategories(flow.dataCategories) !== filters.sensitivity) return false;
      }
      if (filters.categories.size > 0) {
        const hit = flow.dataCategories.some((c) => filters.categories.has(c));
        if (!hit) return false;
      }
      return true;
    };

    const kept = graphEdges.filter(edgePasses);
    const activeAssetIds = new Set<string>();
    for (const e of kept) {
      activeAssetIds.add(e.source);
      activeAssetIds.add(e.target);
    }

    const focusNeighbours = new Set<string>();
    if (focusedNodeId) {
      focusNeighbours.add(focusedNodeId);
      for (const e of kept) {
        if (e.source === focusedNodeId) focusNeighbours.add(e.target);
        else if (e.target === focusedNodeId) focusNeighbours.add(e.source);
      }
    }

    const displayEdges = graphEdges.map((e): FlowEdgeType => {
      const pass = edgePasses(e);
      const touchesFocus =
        !focusedNodeId || e.source === focusedNodeId || e.target === focusedNodeId;
      return {
        ...e,
        hidden: !pass,
        data: {
          ...e.data!,
          isDimmed: pass && focusedNodeId !== null && !touchesFocus,
        },
      };
    });

    const displayNodes = graphNodes.map((n): AssetNodeType => {
      const hasVisibleEdge = activeAssetIds.has(n.id);
      const dim =
        !hasVisibleEdge ||
        (focusedNodeId !== null && !focusNeighbours.has(n.id));
      return {
        ...n,
        data: {
          ...n.data,
          isDimmed: dim,
          isFocused: focusedNodeId !== null && n.id === focusedNodeId,
        },
      };
    });

    return { displayNodes, displayEdges, visibleEdgeCount: kept.length };
  }, [graphNodes, graphEdges, filters, focusedNodeId]);

  useEffect(() => {
    setNodes(displayNodes);
    setEdges(displayEdges);
  }, [displayNodes, displayEdges, setNodes, setEdges]);

  const handleNodeMouseEnter: NodeMouseHandler<AssetNodeType> = useCallback(
    (_e, node) => setFocusedNodeId(node.id),
    []
  );
  const handleNodeMouseLeave: NodeMouseHandler<AssetNodeType> = useCallback(
    () => setFocusedNodeId(null),
    []
  );

  if (isLoading) {
    return <div className="text-sm text-slate-500 p-8">Laying out…</div>;
  }

  return (
    <div className="relative h-[calc(100vh-80px)] w-full">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onNodeMouseEnter={handleNodeMouseEnter}
        onNodeMouseLeave={handleNodeMouseLeave}
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        fitView
        fitViewOptions={{ padding: 0.2 }}
        minZoom={0.1}
        maxZoom={2}
        defaultEdgeOptions={{ type: "flowEdge" }}
        proOptions={{ hideAttribution: true }}
        style={{ backgroundColor: "#ffffff" }}
      >
        <Background color="#e2e8f0" gap={22} size={1} />
        <Controls
          showInteractive={false}
          className="!bg-white !border-slate-200 [&>button]:!bg-white [&>button]:!border-slate-200 [&>button]:!text-slate-700 [&>button:hover]:!bg-slate-100"
          style={{ borderRadius: 0 }}
        />
        <MiniMap
          nodeColor={(n) => {
            const asset = (n.data as { asset: AssetData }).asset;
            const color: Record<string, string> = {
              APPLICATION: "#0e4a6e",
              CLOUD_SERVICE: "#2563eb",
              DATABASE: "#4338ca",
              FILE_SYSTEM: "#64748b",
              THIRD_PARTY: "#d97706",
              PHYSICAL: "#78716c",
              OTHER: "#94a3b8",
            };
            return color[asset.type] ?? "#94a3b8";
          }}
          maskColor="rgba(248, 250, 252, 0.8)"
          className="!bg-white !border-slate-200"
          style={{ borderRadius: 0 }}
        />

        <Panel position="top-left" className="max-w-[calc(100%-40px)]">
          <FlowFilterToolbar
            filters={filters}
            onChange={setFilters}
            edgeCount={visibleEdgeCount}
            totalEdges={graphEdges.length}
          />
        </Panel>

        <svg style={{ position: "absolute", top: 0, left: 0, width: 0, height: 0 }}>
          <defs>
            {[
              { id: "arrowhead-special", color: "#dc2626" },
              { id: "arrowhead-sensitive", color: "#d97706" },
              { id: "arrowhead-general", color: "#2563eb" },
              { id: "arrowhead-none", color: "#94a3b8" },
            ].map((m) => (
              <marker
                key={m.id}
                id={m.id}
                markerWidth="12"
                markerHeight="12"
                refX="10"
                refY="6"
                orient="auto"
              >
                <path d="M2,2 L10,6 L2,10 L4,6 Z" fill={m.color} />
              </marker>
            ))}
          </defs>
        </svg>
      </ReactFlow>
    </div>
  );
}
