// scripts/demo/verticals/media.ts
// Vertical demo scenario: Herald Digital Media — European publisher
// 2M readers, 150K subscribers, consent-driven ad tech (TCF 2.2)

import type { VerticalScenario } from "../types";

export const scenario: VerticalScenario = {
  key: "media",
  orgName: "Herald Digital Media",
  orgSlug: "demo-media",
  domain: "heralddigital.eu",
  jurisdictionCodes: ["GDPR"],

  // ── Users ───────────────────────────────────────────────────
  users: [
    {
      id: "media-user-owner",
      ref: "owner",
      name: "Demo User",
      email: "demo-media@privacysuite.example",
      role: "OWNER",
    },
    {
      id: "media-user-dpo",
      ref: "dpo",
      name: "Clara Bergstr\u00f6m",
      email: "clara.bergstrom@heralddigital.eu",
      role: "PRIVACY_OFFICER",
    },
    {
      id: "media-user-admin",
      ref: "admin",
      name: "Jean-Pierre Dubois",
      email: "jp.dubois@heralddigital.eu",
      role: "ADMIN",
    },
    {
      id: "media-user-member1",
      ref: "member1",
      name: "Marta Kowalska",
      email: "marta.kowalska@heralddigital.eu",
      role: "MEMBER",
    },
    {
      id: "media-user-member2",
      ref: "member2",
      name: "Oliver Hayes",
      email: "oliver.hayes@heralddigital.eu",
      role: "MEMBER",
    },
  ],

  // ── Data Assets ─────────────────────────────────────────────
  assets: [
    {
      id: "media-asset-subscriber-db",
      name: "Subscriber Database",
      description:
        "PostgreSQL database storing subscriber accounts, preferences, reading history, and subscription tiers for 150K paying subscribers.",
      type: "DATABASE",
      owner: "Engineering",
      location: "EU (Frankfurt, AWS RDS)",
      hostingType: "cloud",
      vendor: "Amazon Web Services",
      isProduction: true,
    },
    {
      id: "media-asset-cms",
      name: "Content Management System (WordPress VIP)",
      description:
        "Enterprise WordPress VIP instance hosting articles, editorial content, author profiles, and media assets. Powers heralddigital.eu.",
      type: "APPLICATION",
      owner: "Editorial",
      location: "EU (WordPress VIP EU infrastructure)",
      hostingType: "cloud",
      vendor: "WordPress VIP",
      isProduction: true,
    },
    {
      id: "media-asset-ad-platform",
      name: "Programmatic Advertising (Google Ad Manager)",
      description:
        "Ad serving and real-time bidding (RTB) platform. Processes reader behavioral data, ad interactions, and consent signals via TCF 2.2. DPIA focus area.",
      type: "THIRD_PARTY",
      owner: "Ad Operations",
      location: "US (Google Cloud)",
      hostingType: "cloud",
      vendor: "Google Ad Manager",
      isProduction: true,
    },
    {
      id: "media-asset-consent-platform",
      name: "Consent Management (Didomi)",
      description:
        "TCF 2.2 compliant consent management platform. Collects, stores, and propagates consent signals across the ad tech stack and analytics tools.",
      type: "THIRD_PARTY",
      owner: "Privacy & Legal",
      location: "EU (Didomi EU infrastructure)",
      hostingType: "cloud",
      vendor: "Didomi",
      isProduction: true,
    },
    {
      id: "media-asset-email-platform",
      name: "Email Marketing (Mailchimp)",
      description:
        "Newsletter and campaign management platform. Manages 150K+ subscriber email lists, open/click tracking, and segmentation.",
      type: "THIRD_PARTY",
      owner: "Marketing",
      location: "US (Mailchimp/Intuit infrastructure)",
      hostingType: "cloud",
      vendor: "Mailchimp",
      isProduction: true,
    },
    {
      id: "media-asset-analytics",
      name: "Reader Analytics (Piano)",
      description:
        "Subscription analytics and paywall optimization platform. Tracks reader engagement, content consumption patterns, and conversion funnels.",
      type: "THIRD_PARTY",
      owner: "Product",
      location: "EU (Piano EU data center)",
      hostingType: "cloud",
      vendor: "Piano",
      isProduction: true,
    },
    {
      id: "media-asset-podcast",
      name: "Podcast Platform (Spotify for Podcasters)",
      description:
        "Audio content hosting and distribution for Herald Digital's podcast network. Tracks downloads, listening duration, and geographic distribution.",
      type: "THIRD_PARTY",
      owner: "Audio & Podcasts",
      location: "US (Spotify infrastructure)",
      hostingType: "cloud",
      vendor: "Spotify",
      isProduction: true,
    },
    {
      id: "media-asset-crm",
      name: "CRM & Ad Sales (HubSpot)",
      description:
        "Customer relationship management for direct ad sales, agency contacts, and advertiser pipeline tracking.",
      type: "THIRD_PARTY",
      owner: "Commercial",
      location: "EU (HubSpot EU data center)",
      hostingType: "cloud",
      vendor: "HubSpot",
      isProduction: true,
    },
    {
      id: "media-asset-billing",
      name: "Subscription Billing (Stripe)",
      description:
        "Payment processing for digital subscriptions. Handles recurring billing, card tokenization, and subscription lifecycle management.",
      type: "THIRD_PARTY",
      owner: "Finance",
      location: "EU (Stripe EU infrastructure)",
      hostingType: "cloud",
      vendor: "Stripe",
      isProduction: true,
    },
    {
      id: "media-asset-comment-system",
      name: "Reader Comments Platform",
      description:
        "Moderated reader comments system integrated into article pages. Stores commenter identities, IP addresses, and user-generated content.",
      type: "APPLICATION",
      owner: "Community",
      location: "EU (Frankfurt, AWS)",
      hostingType: "cloud",
      vendor: "Internal",
      isProduction: true,
    },
  ],

  // ── Data Elements ───────────────────────────────────────────
  elements: [
    // Subscriber DB elements
    {
      id: "media-elem-subscriber-db-email",
      dataAssetId: "media-asset-subscriber-db",
      name: "Subscriber Email Address",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Contract",
    },
    {
      id: "media-elem-subscriber-db-name",
      dataAssetId: "media-asset-subscriber-db",
      name: "Subscriber Full Name",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Contract",
    },
    {
      id: "media-elem-subscriber-db-reading-history",
      dataAssetId: "media-asset-subscriber-db",
      name: "Reading History",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-subscriber-db-preferences",
      dataAssetId: "media-asset-subscriber-db",
      name: "Content Preferences & Topics",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-subscriber-db-subscription-tier",
      dataAssetId: "media-asset-subscriber-db",
      name: "Subscription Tier & Status",
      category: "FINANCIAL",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Contract",
    },
    // Ad platform elements
    {
      id: "media-elem-ad-platform-ad-interactions",
      dataAssetId: "media-asset-ad-platform",
      name: "Ad Interaction Data (Impressions, Clicks)",
      category: "BEHAVIORAL",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 365,
      legalBasis: "Consent (TCF 2.2)",
    },
    {
      id: "media-elem-ad-platform-ip-address",
      dataAssetId: "media-asset-ad-platform",
      name: "IP Address (Truncated)",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 90,
      legalBasis: "Consent (TCF 2.2)",
    },
    {
      id: "media-elem-ad-platform-device-ids",
      dataAssetId: "media-asset-ad-platform",
      name: "Device & Browser Identifiers",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 365,
      legalBasis: "Consent (TCF 2.2)",
    },
    {
      id: "media-elem-ad-platform-bid-data",
      dataAssetId: "media-asset-ad-platform",
      name: "RTB Bid Request Data",
      category: "BEHAVIORAL",
      sensitivity: "RESTRICTED",
      isPersonalData: true,
      retentionDays: 30,
      legalBasis: "Consent (TCF 2.2)",
    },
    // Consent platform elements
    {
      id: "media-elem-consent-platform-signals",
      dataAssetId: "media-asset-consent-platform",
      name: "Consent Signals (TCF 2.2 TC String)",
      category: "OTHER",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legal Obligation",
    },
    {
      id: "media-elem-consent-platform-history",
      dataAssetId: "media-asset-consent-platform",
      name: "Consent Change History & Timestamps",
      category: "OTHER",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 1825,
      legalBasis: "Legal Obligation",
    },
    // Email platform elements
    {
      id: "media-elem-email-platform-newsletter-prefs",
      dataAssetId: "media-asset-email-platform",
      name: "Newsletter Preferences & Subscriptions",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Consent",
    },
    {
      id: "media-elem-email-platform-engagement",
      dataAssetId: "media-asset-email-platform",
      name: "Email Engagement (Opens, Clicks)",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 365,
      legalBasis: "Consent",
    },
    // Analytics elements
    {
      id: "media-elem-analytics-engagement",
      dataAssetId: "media-asset-analytics",
      name: "Reader Engagement Metrics",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-analytics-conversion",
      dataAssetId: "media-asset-analytics",
      name: "Paywall Conversion & Funnel Data",
      category: "BEHAVIORAL",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legitimate Interests",
    },
    // Podcast elements
    {
      id: "media-elem-podcast-listening",
      dataAssetId: "media-asset-podcast",
      name: "Podcast Listening Data (Downloads, Duration)",
      category: "BEHAVIORAL",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 730,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-podcast-geo",
      dataAssetId: "media-asset-podcast",
      name: "Listener Geographic Distribution",
      category: "LOCATION",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 365,
      legalBasis: "Legitimate Interests",
    },
    // CRM elements
    {
      id: "media-elem-crm-advertiser-contacts",
      dataAssetId: "media-asset-crm",
      name: "Advertiser & Agency Contacts",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-crm-deal-pipeline",
      dataAssetId: "media-asset-crm",
      name: "Ad Sales Deal Pipeline",
      category: "FINANCIAL",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: false,
      retentionDays: 1825,
      legalBasis: "Legitimate Interests",
    },
    // Billing elements
    {
      id: "media-elem-billing-payment",
      dataAssetId: "media-asset-billing",
      name: "Payment Card Tokens & Billing Address",
      category: "FINANCIAL",
      sensitivity: "RESTRICTED",
      isPersonalData: true,
      retentionDays: 1825,
      legalBasis: "Contract",
    },
    {
      id: "media-elem-billing-invoices",
      dataAssetId: "media-asset-billing",
      name: "Subscription Invoices & Transaction History",
      category: "FINANCIAL",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 2555,
      legalBasis: "Legal Obligation",
    },
    // Comment system elements
    {
      id: "media-elem-comment-system-identity",
      dataAssetId: "media-asset-comment-system",
      name: "Commenter Display Name & Profile",
      category: "IDENTIFIERS",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Consent",
    },
    {
      id: "media-elem-comment-system-ip",
      dataAssetId: "media-asset-comment-system",
      name: "Commenter IP Address",
      category: "IDENTIFIERS",
      sensitivity: "CONFIDENTIAL",
      isPersonalData: true,
      retentionDays: 90,
      legalBasis: "Legitimate Interests",
    },
    {
      id: "media-elem-comment-system-content",
      dataAssetId: "media-asset-comment-system",
      name: "Comment Text (User-Generated Content)",
      category: "OTHER",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 1095,
      legalBasis: "Consent",
    },
    // CMS elements
    {
      id: "media-elem-cms-author-profiles",
      dataAssetId: "media-asset-cms",
      name: "Author & Journalist Profiles",
      category: "EMPLOYMENT",
      sensitivity: "INTERNAL",
      isPersonalData: true,
      retentionDays: 1825,
      legalBasis: "Contract",
    },
  ],

  // ── Processing Activities ───────────────────────────────────
  activities: [
    {
      id: "media-pa-content-delivery",
      name: "Content Publishing & Delivery",
      description:
        "Publishing articles, multimedia, and editorial content to readers via heralddigital.eu. Includes article personalization based on reading history and content preferences.",
      purpose: "Deliver journalism and editorial content to readers and subscribers",
      legalBasis: "LEGITIMATE_INTERESTS",
      legalBasisDetail:
        "Legitimate interest in operating a news publication and delivering relevant content to readers (Art. 6(1)(f)). LIA completed — reader interests balanced against editorial mission.",
      dataSubjects: ["Website visitors", "Subscribers", "Registered readers"],
      categories: ["IDENTIFIERS", "BEHAVIORAL"],
      recipients: ["WordPress VIP (hosting)", "Piano (analytics)", "CDN providers"],
      retentionPeriod: "2 years for engagement data, articles retained indefinitely",
      retentionDays: 730,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-11-15",
      nextReviewAt: "2026-11-15",
      assetIds: ["media-asset-cms", "media-asset-subscriber-db", "media-asset-analytics"],
    },
    {
      id: "media-pa-programmatic-ads",
      name: "Programmatic Advertising & Real-Time Bidding",
      description:
        "Serving targeted advertising via Google Ad Manager using real-time bidding (RTB). Reader behavioral profiles, ad interaction data, and device identifiers are shared with demand-side platforms (DSPs) in bid requests. Consent managed via TCF 2.2 through Didomi CMP. DPIA required due to profiling at scale.",
      purpose:
        "Revenue generation through targeted programmatic advertising on heralddigital.eu",
      legalBasis: "CONSENT",
      legalBasisDetail:
        "Explicit consent obtained via TCF 2.2 consent management platform (Didomi). Consent covers Purpose 1-10 per IAB TCF framework. Non-consenting users see contextual ads only.",
      dataSubjects: ["Website visitors", "Subscribers", "App users"],
      categories: ["IDENTIFIERS", "BEHAVIORAL", "LOCATION"],
      recipients: [
        "Google Ad Manager (ad server)",
        "Demand-side platforms (DSPs)",
        "Supply-side platforms (SSPs)",
        "Data management platforms (DMPs)",
      ],
      retentionPeriod: "30 days for bid request data, 1 year for aggregate reporting",
      retentionDays: 365,
      automatedDecisionMaking: true,
      automatedDecisionDetail:
        "Automated profiling for ad targeting based on reading behavior, content preferences, and inferred interests. No legal or similarly significant effects — limited to ad personalization with consent-only fallback to contextual.",
      isActive: true,
      lastReviewedAt: "2025-10-20",
      nextReviewAt: "2026-04-20",
      assetIds: [
        "media-asset-ad-platform",
        "media-asset-consent-platform",
        "media-asset-subscriber-db",
      ],
    },
    {
      id: "media-pa-subscription-mgmt",
      name: "Subscription Management",
      description:
        "Managing digital subscription lifecycle including sign-up, billing, tier changes, cancellations, and payment processing for 150K subscribers.",
      purpose: "Fulfil subscription contracts and manage subscriber accounts",
      legalBasis: "CONTRACT",
      legalBasisDetail:
        "Processing necessary for the performance of the subscription contract (Art. 6(1)(b)). Subscriber data retained for the duration of the contract plus statutory retention periods.",
      dataSubjects: ["Subscribers"],
      categories: ["IDENTIFIERS", "FINANCIAL"],
      recipients: ["Stripe (payment processing)", "Internal finance team"],
      retentionPeriod: "Duration of subscription + 7 years for financial records",
      retentionDays: 2555,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-09-01",
      nextReviewAt: "2026-09-01",
      assetIds: ["media-asset-subscriber-db", "media-asset-billing"],
    },
    {
      id: "media-pa-newsletter",
      name: "Newsletter & Email Marketing",
      description:
        "Sending editorial newsletters, breaking news alerts, and marketing emails to opted-in subscribers. Includes open/click tracking for engagement analysis.",
      purpose: "Distribute editorial newsletters and promotional content to consenting readers",
      legalBasis: "CONSENT",
      legalBasisDetail:
        "Explicit opt-in consent for each newsletter type (Art. 6(1)(a)). Double opt-in process with unsubscribe link in every email. ePrivacy Directive compliant.",
      dataSubjects: ["Newsletter subscribers", "Registered readers"],
      categories: ["IDENTIFIERS", "BEHAVIORAL"],
      recipients: ["Mailchimp (email delivery)", "Internal editorial team"],
      retentionPeriod: "Until consent withdrawal + 30 days for suppression list",
      retentionDays: 730,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-12-01",
      nextReviewAt: "2026-06-01",
      assetIds: ["media-asset-email-platform", "media-asset-subscriber-db"],
    },
    {
      id: "media-pa-reader-analytics",
      name: "Reader Analytics & Engagement",
      description:
        "Analyzing reader engagement patterns, content performance, paywall conversion rates, and subscription funnel optimization using Piano analytics.",
      purpose:
        "Improve editorial quality and optimize subscription conversion through reader behavior analysis",
      legalBasis: "LEGITIMATE_INTERESTS",
      legalBasisDetail:
        "Legitimate interest in understanding reader engagement to improve journalism and sustain the publication (Art. 6(1)(f)). LIA completed — aggregated analytics with pseudonymization.",
      dataSubjects: ["Website visitors", "Subscribers"],
      categories: ["BEHAVIORAL", "IDENTIFIERS"],
      recipients: ["Piano (analytics platform)", "Internal product & editorial teams"],
      retentionPeriod: "2 years for individual-level data, indefinite for aggregated metrics",
      retentionDays: 730,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-10-01",
      nextReviewAt: "2026-10-01",
      assetIds: ["media-asset-analytics", "media-asset-subscriber-db"],
    },
    {
      id: "media-pa-employment",
      name: "Employment Records",
      description:
        "Processing of journalist and staff employment data including contracts, payroll, and HR records.",
      purpose: "Fulfil employment obligations and manage staff",
      legalBasis: "CONTRACT",
      legalBasisDetail:
        "Processing necessary for the performance of employment contracts (Art. 6(1)(b)) and legal obligations (Art. 6(1)(c)) for payroll and tax.",
      dataSubjects: ["Employees", "Journalists", "Freelancers"],
      categories: ["IDENTIFIERS", "EMPLOYMENT", "FINANCIAL"],
      recipients: ["Internal HR", "Payroll provider", "Tax authorities"],
      retentionPeriod: "Duration of employment + 7 years",
      retentionDays: 2555,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-08-15",
      nextReviewAt: "2026-08-15",
      assetIds: ["media-asset-subscriber-db"],
    },
    {
      id: "media-pa-podcast-distribution",
      name: "Podcast Publishing & Analytics",
      description:
        "Hosting and distributing Herald Digital podcast episodes via Spotify for Podcasters. Aggregate listener analytics including download counts, geographic distribution, and listening duration.",
      purpose: "Publish and distribute audio journalism content, measure audience reach",
      legalBasis: "LEGITIMATE_INTERESTS",
      legalBasisDetail:
        "Legitimate interest in distributing editorial audio content and measuring audience engagement (Art. 6(1)(f)). Analytics primarily aggregated — individual listener data limited to platform defaults.",
      dataSubjects: ["Podcast listeners", "App users"],
      categories: ["BEHAVIORAL", "LOCATION"],
      recipients: ["Spotify for Podcasters (hosting)", "Apple Podcasts", "Google Podcasts"],
      retentionPeriod: "2 years for analytics, episodes retained indefinitely",
      retentionDays: 730,
      automatedDecisionMaking: false,
      isActive: true,
      lastReviewedAt: "2025-11-01",
      nextReviewAt: "2026-11-01",
      assetIds: ["media-asset-podcast"],
    },
  ],

  // ── Data Flows ──────────────────────────────────────────────
  flows: [
    {
      id: "media-flow-sub-to-email",
      name: "Subscriber DB to Email Platform",
      description:
        "Subscriber email addresses, names, and newsletter preferences synced to Mailchimp for newsletter delivery.",
      sourceAssetId: "media-asset-subscriber-db",
      destinationAssetId: "media-asset-email-platform",
      dataCategories: ["IDENTIFIERS", "BEHAVIORAL"],
      frequency: "Real-time (webhook on preference change)",
      volume: "~500 records/day",
      encryptionMethod: "TLS 1.3 in transit, AES-256 at rest",
      isAutomated: true,
    },
    {
      id: "media-flow-cms-to-ad",
      name: "CMS to Ad Platform",
      description:
        "Article metadata and page context sent to Google Ad Manager for contextual ad targeting and placement.",
      sourceAssetId: "media-asset-cms",
      destinationAssetId: "media-asset-ad-platform",
      dataCategories: ["OTHER"],
      frequency: "Per page view (real-time)",
      volume: "~5M ad requests/day",
      encryptionMethod: "TLS 1.3 in transit",
      isAutomated: true,
    },
    {
      id: "media-flow-consent-to-ad",
      name: "Consent Platform to Ad Platform",
      description:
        "TCF 2.2 consent strings propagated from Didomi CMP to Google Ad Manager to control ad targeting and vendor access.",
      sourceAssetId: "media-asset-consent-platform",
      destinationAssetId: "media-asset-ad-platform",
      dataCategories: ["OTHER"],
      frequency: "Per page view (real-time via TCF API)",
      volume: "~5M consent signals/day",
      encryptionMethod: "TLS 1.3 in transit",
      isAutomated: true,
    },
    {
      id: "media-flow-consent-to-analytics",
      name: "Consent Platform to Analytics",
      description:
        "Consent signals from Didomi determine which tracking features are enabled in Piano analytics.",
      sourceAssetId: "media-asset-consent-platform",
      destinationAssetId: "media-asset-analytics",
      dataCategories: ["OTHER"],
      frequency: "Per session (real-time)",
      volume: "~2M sessions/day",
      encryptionMethod: "TLS 1.3 in transit",
      isAutomated: true,
    },
    {
      id: "media-flow-sub-to-analytics",
      name: "Subscriber DB to Analytics",
      description:
        "Pseudonymized subscriber identifiers sent to Piano for subscription funnel analysis and paywall optimization.",
      sourceAssetId: "media-asset-subscriber-db",
      destinationAssetId: "media-asset-analytics",
      dataCategories: ["IDENTIFIERS", "BEHAVIORAL"],
      frequency: "Real-time (client-side SDK)",
      volume: "~500K events/day",
      encryptionMethod: "TLS 1.3 in transit, pseudonymized IDs",
      isAutomated: true,
    },
    {
      id: "media-flow-sub-to-billing",
      name: "Subscriber DB to Billing",
      description:
        "Subscriber billing details and subscription tier synced to Stripe for payment processing and recurring charges.",
      sourceAssetId: "media-asset-subscriber-db",
      destinationAssetId: "media-asset-billing",
      dataCategories: ["IDENTIFIERS", "FINANCIAL"],
      frequency: "On subscription change (event-driven)",
      volume: "~200 transactions/day",
      encryptionMethod: "TLS 1.3 in transit, PCI DSS compliant tokenization",
      isAutomated: true,
    },
    {
      id: "media-flow-crm-to-ad",
      name: "CRM to Ad Platform",
      description:
        "Direct-sold campaign configurations and advertiser data pushed from HubSpot to Google Ad Manager for premium ad placement.",
      sourceAssetId: "media-asset-crm",
      destinationAssetId: "media-asset-ad-platform",
      dataCategories: ["IDENTIFIERS", "FINANCIAL"],
      frequency: "Daily batch sync",
      volume: "~50 campaign records/day",
      encryptionMethod: "TLS 1.3 in transit, API key authentication",
      isAutomated: true,
    },
    {
      id: "media-flow-comments-to-sub",
      name: "Comment System to Subscriber DB",
      description:
        "Commenter authentication linked to subscriber accounts for verified commenting and reputation tracking.",
      sourceAssetId: "media-asset-comment-system",
      destinationAssetId: "media-asset-subscriber-db",
      dataCategories: ["IDENTIFIERS"],
      frequency: "Per comment submission (real-time)",
      volume: "~2K comments/day",
      encryptionMethod: "TLS 1.3 in transit",
      isAutomated: true,
    },
  ],

  // ── International Transfers ─────────────────────────────────
  transfers: [
    {
      id: "media-transfer-google-rtb",
      name: "EU to US: Google Ad Manager (RTB)",
      description:
        "Reader behavioral data and ad interaction signals transferred to Google Ad Manager US infrastructure for real-time bidding and programmatic ad delivery. SCCs in place with supplementary measures.",
      destinationCountry: "US",
      destinationOrg: "Google LLC",
      mechanism: "STANDARD_CONTRACTUAL_CLAUSES",
      safeguards:
        "EU SCCs (Module 1: Controller-to-Controller). Supplementary measures include data pseudonymization in bid requests, IP truncation, and contractual restrictions on US government access requests. Google compliant with EU-US Data Privacy Framework.",
      tiaCompleted: true,
      tiaDate: "2025-06-15",
      activityId: "media-pa-programmatic-ads",
    },
    {
      id: "media-transfer-mailchimp",
      name: "EU to US: Mailchimp (Email Marketing)",
      description:
        "Subscriber email addresses, names, and newsletter preferences transferred to Mailchimp US servers for email campaign delivery.",
      destinationCountry: "US",
      destinationOrg: "The Rocket Science Group LLC (Intuit)",
      mechanism: "STANDARD_CONTRACTUAL_CLAUSES",
      safeguards:
        "EU SCCs (Module 2: Controller-to-Processor). DPA in place. Mailchimp certified under EU-US Data Privacy Framework. Data encrypted in transit and at rest.",
      tiaCompleted: true,
      tiaDate: "2025-07-01",
      activityId: "media-pa-newsletter",
    },
    {
      id: "media-transfer-spotify",
      name: "EU to US: Spotify (Podcast Hosting)",
      description:
        "Podcast episode files and aggregate listener analytics transferred to Spotify US infrastructure for hosting and distribution.",
      destinationCountry: "US",
      destinationOrg: "Spotify AB",
      mechanism: "STANDARD_CONTRACTUAL_CLAUSES",
      safeguards:
        "EU SCCs (Module 2: Controller-to-Processor). Podcast analytics primarily aggregated. Individual listener data limited to platform-level metrics with no direct identifiers.",
      tiaCompleted: true,
      tiaDate: "2025-08-10",
      activityId: "media-pa-podcast-distribution",
    },
  ],

  // ── Vendors ─────────────────────────────────────────────────
  vendors: [
    {
      id: "media-vendor-google-ad-manager",
      name: "Google Ad Manager",
      description:
        "Programmatic ad serving and real-time bidding platform. Processes reader behavioral data for targeted advertising via TCF 2.2 consent.",
      website: "https://admanager.google.com",
      status: "ACTIVE",
      riskTier: "HIGH",
      riskScore: 72,
      primaryContact: "Google Privacy Team",
      contactEmail: "privacy@google.com",
      categories: ["Advertising Technology", "Ad Serving"],
      dataProcessed: ["IDENTIFIERS", "BEHAVIORAL", "LOCATION"],
      countries: ["US", "IE"],
      certifications: ["SOC 2 Type II", "ISO 27001", "EU-US DPF"],
      lastAssessedAt: "2025-10-20",
      nextReviewAt: "2026-04-20",
    },
    {
      id: "media-vendor-mailchimp",
      name: "Mailchimp (Intuit)",
      description:
        "Email marketing and newsletter delivery platform for subscriber communications and editorial content distribution.",
      website: "https://mailchimp.com",
      status: "ACTIVE",
      riskTier: "MEDIUM",
      riskScore: 45,
      primaryContact: "Mailchimp DPA Team",
      contactEmail: "privacy@mailchimp.com",
      categories: ["Email Marketing", "Marketing Automation"],
      dataProcessed: ["IDENTIFIERS", "BEHAVIORAL"],
      countries: ["US"],
      certifications: ["SOC 2 Type II", "EU-US DPF"],
      lastAssessedAt: "2025-09-15",
      nextReviewAt: "2026-03-15",
    },
    {
      id: "media-vendor-didomi",
      name: "Didomi",
      description:
        "TCF 2.2 compliant consent management platform. Collects and propagates consent signals across the ad tech and analytics stack.",
      website: "https://www.didomi.io",
      status: "ACTIVE",
      riskTier: "LOW",
      riskScore: 18,
      primaryContact: "Didomi Privacy Office",
      contactEmail: "dpo@didomi.io",
      categories: ["Consent Management", "Privacy Technology"],
      dataProcessed: ["IDENTIFIERS", "OTHER"],
      countries: ["FR"],
      certifications: ["SOC 2 Type II", "ISO 27001", "IAB TCF 2.2 CMP"],
      lastAssessedAt: "2025-11-01",
      nextReviewAt: "2026-05-01",
    },
    {
      id: "media-vendor-wordpress-vip",
      name: "WordPress VIP",
      description:
        "Enterprise managed WordPress hosting for heralddigital.eu. Hosts all editorial content, author profiles, and media assets.",
      website: "https://wpvip.com",
      status: "ACTIVE",
      riskTier: "LOW",
      riskScore: 22,
      primaryContact: "WP VIP Enterprise Support",
      contactEmail: "security@wpvip.com",
      categories: ["Content Management", "Hosting"],
      dataProcessed: ["IDENTIFIERS", "EMPLOYMENT"],
      countries: ["US", "EU"],
      certifications: ["SOC 2 Type II", "FedRAMP"],
      lastAssessedAt: "2025-08-01",
      nextReviewAt: "2026-08-01",
    },
    {
      id: "media-vendor-piano",
      name: "Piano",
      description:
        "Reader analytics, paywall management, and subscription optimization platform. Tracks engagement metrics and conversion funnels.",
      website: "https://piano.io",
      status: "ACTIVE",
      riskTier: "MEDIUM",
      riskScore: 38,
      primaryContact: "Piano Data Protection",
      contactEmail: "privacy@piano.io",
      categories: ["Analytics", "Subscription Management"],
      dataProcessed: ["IDENTIFIERS", "BEHAVIORAL"],
      countries: ["EU", "US"],
      certifications: ["SOC 2 Type II"],
      lastAssessedAt: "2025-10-01",
      nextReviewAt: "2026-04-01",
    },
    {
      id: "media-vendor-hubspot",
      name: "HubSpot",
      description:
        "CRM and ad sales management platform for direct advertising relationships, agency contacts, and campaign pipeline.",
      website: "https://www.hubspot.com",
      status: "ACTIVE",
      riskTier: "MEDIUM",
      riskScore: 35,
      primaryContact: "HubSpot Privacy Team",
      contactEmail: "privacy@hubspot.com",
      categories: ["CRM", "Sales Automation"],
      dataProcessed: ["IDENTIFIERS", "FINANCIAL"],
      countries: ["US", "DE"],
      certifications: ["SOC 2 Type II", "ISO 27001", "EU-US DPF"],
      lastAssessedAt: "2025-07-15",
      nextReviewAt: "2026-07-15",
    },
    {
      id: "media-vendor-spotify",
      name: "Spotify for Podcasters",
      description:
        "Podcast hosting and distribution platform for Herald Digital's audio content. Provides listener analytics and audience metrics.",
      website: "https://podcasters.spotify.com",
      status: "ACTIVE",
      riskTier: "LOW",
      riskScore: 25,
      primaryContact: "Spotify Privacy Office",
      contactEmail: "privacy@spotify.com",
      categories: ["Podcast Hosting", "Content Distribution"],
      dataProcessed: ["BEHAVIORAL", "LOCATION"],
      countries: ["SE", "US"],
      certifications: ["SOC 2 Type II", "ISO 27001"],
      lastAssessedAt: "2025-08-10",
      nextReviewAt: "2026-08-10",
    },
    {
      id: "media-vendor-stripe",
      name: "Stripe",
      description:
        "Payment processing for digital subscriptions. Handles card tokenization, recurring billing, and subscription lifecycle.",
      website: "https://stripe.com",
      status: "ACTIVE",
      riskTier: "MEDIUM",
      riskScore: 40,
      primaryContact: "Stripe Privacy Team",
      contactEmail: "privacy@stripe.com",
      categories: ["Payment Processing", "Billing"],
      dataProcessed: ["IDENTIFIERS", "FINANCIAL"],
      countries: ["US", "IE"],
      certifications: ["PCI DSS Level 1", "SOC 2 Type II", "ISO 27001", "EU-US DPF"],
      lastAssessedAt: "2025-09-01",
      nextReviewAt: "2026-03-01",
    },
  ],

  // ── Contracts ───────────────────────────────────────────────
  contracts: [
    {
      id: "media-contract-google-dpa",
      vendorId: "media-vendor-google-ad-manager",
      type: "DPA",
      status: "ACTIVE",
      name: "Google Ad Manager Data Processing Agreement",
      description:
        "DPA covering programmatic advertising, RTB data processing, and TCF 2.2 consent signal handling. Includes EU SCCs as transfer mechanism.",
      startDate: "2024-01-15",
      endDate: "2026-01-15",
      autoRenewal: true,
      value: 0,
      currency: "EUR",
    },
    {
      id: "media-contract-mailchimp-dpa",
      vendorId: "media-vendor-mailchimp",
      type: "DPA",
      status: "ACTIVE",
      name: "Mailchimp Data Processing Agreement",
      description:
        "DPA for newsletter and email marketing subscriber data processing. Includes EU SCCs.",
      startDate: "2024-03-01",
      endDate: "2026-03-01",
      autoRenewal: true,
      value: 4800,
      currency: "EUR",
    },
    {
      id: "media-contract-didomi-msa",
      vendorId: "media-vendor-didomi",
      type: "MSA",
      status: "ACTIVE",
      name: "Didomi CMP Master Service Agreement",
      description:
        "MSA for TCF 2.2 consent management platform license and support. Enterprise tier with SLA.",
      startDate: "2024-06-01",
      endDate: "2026-06-01",
      autoRenewal: true,
      value: 18000,
      currency: "EUR",
    },
    {
      id: "media-contract-stripe-dpa",
      vendorId: "media-vendor-stripe",
      type: "DPA",
      status: "ACTIVE",
      name: "Stripe Data Processing Agreement",
      description:
        "DPA for payment processing of subscriber billing data. PCI DSS compliant.",
      startDate: "2024-02-01",
      endDate: "2027-02-01",
      autoRenewal: true,
      value: 0,
      currency: "EUR",
    },
    {
      id: "media-contract-piano-msa",
      vendorId: "media-vendor-piano",
      type: "MSA",
      status: "ACTIVE",
      name: "Piano Analytics & Paywall MSA",
      description:
        "Master service agreement for reader analytics, paywall management, and subscription optimization platform.",
      startDate: "2024-04-01",
      endDate: "2026-04-01",
      autoRenewal: true,
      value: 36000,
      currency: "EUR",
    },
  ],

  // ── DSAR Intake Form ────────────────────────────────────────
  intakeForm: {
    name: "Herald Digital Privacy Request Form",
    slug: "privacy-request-media",
    title: "Herald Digital Media Privacy Request",
    description:
      "Submit a privacy request to Herald Digital Media. We will acknowledge your request within 3 business days and respond within 30 days as required by GDPR.",
  },

  // ── DSARs ───────────────────────────────────────────────────
  dsars: [
    {
      id: "media-dsar-1",
      publicId: "DSAR-HDM-2025-001",
      type: "ACCESS",
      status: "COMPLETED",
      requesterName: "Annika Lindgren",
      requesterEmail: "annika.lindgren@gmail.example",
      relationship: "Subscriber",
      description:
        "I am a long-time subscriber and would like to access all data you hold about me, including my reading history, content preferences, ad targeting profile, and subscription records.",
      receivedAt: "2025-09-15T10:30:00Z",
      acknowledgedAt: "2025-09-16T09:00:00Z",
      dueDate: "2025-10-15T10:30:00Z",
      completedAt: "2025-10-08T14:20:00Z",
      verificationMethod: "Email verification via subscriber account",
      verifiedAt: "2025-09-16T11:00:00Z",
      responseMethod: "Secure download link via email",
      responseNotes:
        "Full data export provided including subscriber profile, reading history (2 years), newsletter engagement data, consent records, and billing history. Ad interaction data aggregated per Google DPA terms.",
      tasks: [
        {
          id: "media-dsar-1-task-1",
          dataAssetId: "media-asset-subscriber-db",
          assignee: "member1",
          title: "Export subscriber profile and reading history",
          description: "Extract subscriber account data, reading history, and content preferences from PostgreSQL.",
          status: "COMPLETED",
          completedAt: "2025-09-22T16:00:00Z",
          notes: "Exported 2 years of reading history (4,823 articles viewed). Profile data and preferences included.",
        },
        {
          id: "media-dsar-1-task-2",
          dataAssetId: "media-asset-ad-platform",
          assignee: "member2",
          title: "Retrieve ad interaction data from Google Ad Manager",
          description: "Request ad targeting profile and interaction history via Google Takeout / DPA process.",
          status: "COMPLETED",
          completedAt: "2025-09-30T11:00:00Z",
          notes: "Google provided aggregated ad interaction data per DPA. Individual bid-level data not available per TCF data minimization.",
        },
        {
          id: "media-dsar-1-task-3",
          dataAssetId: "media-asset-email-platform",
          assignee: "member1",
          title: "Export newsletter engagement data",
          description: "Extract newsletter subscription preferences and engagement metrics from Mailchimp.",
          status: "COMPLETED",
          completedAt: "2025-09-25T10:00:00Z",
          notes: "Exported subscription to 4 newsletters with open/click history.",
        },
        {
          id: "media-dsar-1-task-4",
          dataAssetId: "media-asset-consent-platform",
          assignee: "dpo",
          title: "Export consent history from Didomi",
          description: "Retrieve full consent change history and current consent status.",
          status: "COMPLETED",
          completedAt: "2025-09-24T09:30:00Z",
          notes: "13 consent events exported spanning 18 months.",
        },
      ],
      communications: [
        {
          id: "media-dsar-1-comm-1",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Acknowledgement of Your Privacy Request (DSAR-HDM-2025-001)",
          content:
            "Dear Ms. Lindgren, We have received your data access request and will respond within 30 days. Your reference number is DSAR-HDM-2025-001.",
          sentAt: "2025-09-16T09:00:00Z",
          sentBy: "dpo",
        },
        {
          id: "media-dsar-1-comm-2",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Your Data Access Request is Ready (DSAR-HDM-2025-001)",
          content:
            "Dear Ms. Lindgren, Your data export is ready for download. Please use the secure link below (valid for 7 days). The export includes your subscriber profile, reading history, newsletter data, consent records, and ad interaction summary.",
          sentAt: "2025-10-08T14:20:00Z",
          sentBy: "dpo",
        },
      ],
    },
    {
      id: "media-dsar-2",
      publicId: "DSAR-HDM-2025-002",
      type: "ERASURE",
      status: "IN_PROGRESS",
      requesterName: "Thomas Richter",
      requesterEmail: "t.richter@protonmail.com",
      relationship: "Subscriber",
      description:
        "I request the complete deletion of all my personal data under Article 17 GDPR. I was mentioned in a reader comments section in connection with a news article and want everything removed including my subscriber account.",
      receivedAt: "2025-12-01T14:00:00Z",
      acknowledgedAt: "2025-12-02T09:15:00Z",
      dueDate: "2025-12-31T14:00:00Z",
      verificationMethod: "Email verification + ID document (redacted)",
      verifiedAt: "2025-12-03T10:30:00Z",
      responseNotes:
        "Complex case: subscriber erasure straightforward, but comment removal intersects with Article 17(3)(a) journalism exemption. DPO review required for editorial content decisions.",
      tasks: [
        {
          id: "media-dsar-2-task-1",
          dataAssetId: "media-asset-subscriber-db",
          assignee: "member1",
          title: "Delete subscriber account and reading history",
          description: "Remove subscriber profile, preferences, and reading history from database.",
          status: "COMPLETED",
          completedAt: "2025-12-10T11:00:00Z",
          notes: "Subscriber account anonymized. Reading history and preferences deleted. Billing records retained for statutory period.",
        },
        {
          id: "media-dsar-2-task-2",
          dataAssetId: "media-asset-comment-system",
          assignee: "dpo",
          title: "Review comment deletion vs journalism exemption (Art. 17(3)(a))",
          description:
            "Assess whether reader comments linked to news articles fall under the journalism exemption to the right to erasure.",
          status: "IN_PROGRESS",
          notes:
            "DPO reviewing 3 comments on political articles. Journalism exemption may apply to comments that form part of public interest reporting. Legal counsel consulted.",
        },
        {
          id: "media-dsar-2-task-3",
          dataAssetId: "media-asset-email-platform",
          assignee: "member2",
          title: "Remove from Mailchimp lists and suppression",
          description: "Delete subscriber from all Mailchimp lists and add to suppression list to prevent re-enrollment.",
          status: "COMPLETED",
          completedAt: "2025-12-08T15:00:00Z",
          notes: "Removed from 3 newsletter lists. Added to suppression list.",
        },
      ],
      communications: [
        {
          id: "media-dsar-2-comm-1",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Acknowledgement of Your Erasure Request (DSAR-HDM-2025-002)",
          content:
            "Dear Mr. Richter, We acknowledge your erasure request. We are processing your request and will respond within 30 days. Please note that certain data may be retained where legal exemptions apply.",
          sentAt: "2025-12-02T09:15:00Z",
          sentBy: "dpo",
        },
        {
          id: "media-dsar-2-comm-2",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Update on Your Erasure Request (DSAR-HDM-2025-002)",
          content:
            "Dear Mr. Richter, Your subscriber account data has been deleted. We are still reviewing your request regarding comments on news articles, as the journalism exemption (Art. 17(3)(a)) may apply. We will provide a final determination shortly.",
          sentAt: "2025-12-12T10:00:00Z",
          sentBy: "dpo",
        },
      ],
    },
    {
      id: "media-dsar-3",
      publicId: "DSAR-HDM-2025-003",
      type: "ERASURE",
      status: "IDENTITY_PENDING",
      requesterName: "Unknown (pseudonym: FreedomReader42)",
      requesterEmail: "freedomreader42@tutanota.com",
      relationship: "Other",
      description:
        "I posted comments on your website under the name FreedomReader42. I never created a subscriber account. I want all my comments and any data you have about me deleted.",
      receivedAt: "2026-01-10T08:45:00Z",
      dueDate: "2026-02-09T08:45:00Z",
      verificationMethod: "Pending identity verification",
      responseNotes:
        "Anonymous commenter claiming deletion rights. Unable to verify identity without subscriber account. Requested additional verification (email used for commenting, IP correlation, specific comment references).",
      tasks: [
        {
          id: "media-dsar-3-task-1",
          dataAssetId: "media-asset-comment-system",
          assignee: "dpo",
          title: "Attempt to verify commenter identity",
          description:
            "Cross-reference claimed pseudonym with comment system records. Request additional proof of identity from the requester.",
          status: "IN_PROGRESS",
          notes:
            "Found 17 comments from FreedomReader42. Asked requester to confirm original email used during commenting and reference specific comment content to verify identity.",
        },
      ],
      communications: [
        {
          id: "media-dsar-3-comm-1",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Identity Verification Required (DSAR-HDM-2025-003)",
          content:
            "Thank you for your privacy request. Since you do not have a subscriber account, we need to verify your identity before proceeding. Please provide: (1) the email address used when posting comments, (2) references to at least two specific comments you posted, and (3) approximate dates of the comments.",
          sentAt: "2026-01-11T10:00:00Z",
          sentBy: "dpo",
        },
        {
          id: "media-dsar-3-comm-2",
          direction: "INBOUND",
          channel: "email",
          subject: "Re: Identity Verification Required (DSAR-HDM-2025-003)",
          content:
            "I don't remember exactly which email I used. I commented on the article about EU digital regulation from November and the one about media freedom in Poland. I shouldn't have to identify myself to exercise my rights.",
          sentAt: "2026-01-14T16:30:00Z",
        },
      ],
    },
    {
      id: "media-dsar-4",
      publicId: "DSAR-HDM-2025-004",
      type: "PORTABILITY",
      status: "SUBMITTED",
      requesterName: "Sofia Papadopoulos",
      requesterEmail: "sofia.p@outlook.example",
      relationship: "Subscriber",
      description:
        "I am switching to another news platform and would like to receive all my data in a machine-readable format so I can transfer my reading preferences, saved articles, and subscription history to the new provider.",
      receivedAt: "2026-02-01T12:00:00Z",
      acknowledgedAt: "2026-02-02T09:00:00Z",
      dueDate: "2026-03-03T12:00:00Z",
      verificationMethod: "Subscriber account login verification",
      verifiedAt: "2026-02-02T11:00:00Z",
      tasks: [
        {
          id: "media-dsar-4-task-1",
          dataAssetId: "media-asset-subscriber-db",
          assignee: "member1",
          title: "Prepare portable data export (JSON/CSV)",
          description:
            "Generate machine-readable export of subscriber data including reading preferences, saved articles list, and subscription history in JSON format.",
          status: "PENDING",
        },
        {
          id: "media-dsar-4-task-2",
          dataAssetId: "media-asset-email-platform",
          assignee: "member2",
          title: "Export newsletter preferences in portable format",
          description:
            "Export newsletter subscription choices and preference data in machine-readable format.",
          status: "PENDING",
        },
      ],
      communications: [
        {
          id: "media-dsar-4-comm-1",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Acknowledgement of Your Data Portability Request (DSAR-HDM-2025-004)",
          content:
            "Dear Ms. Papadopoulos, We acknowledge your data portability request. We will prepare your data in JSON format for easy transfer and will deliver it within 30 days.",
          sentAt: "2026-02-02T09:00:00Z",
          sentBy: "dpo",
        },
      ],
    },
    {
      id: "media-dsar-5",
      publicId: "DSAR-HDM-2025-005",
      type: "ACCESS",
      status: "REJECTED",
      requesterName: "DataRights Bot",
      requesterEmail: "batch-requests@datarights.example",
      relationship: "Other",
      description:
        "Automated DSAR submission on behalf of 2,847 individuals. Requesting access to all personal data held for each data subject listed in the attached CSV file.",
      receivedAt: "2026-01-20T03:00:00Z",
      acknowledgedAt: "2026-01-21T09:00:00Z",
      dueDate: "2026-02-19T03:00:00Z",
      completedAt: "2026-01-25T11:00:00Z",
      responseMethod: "Email response with rejection rationale",
      responseNotes:
        "Rejected as manifestly excessive under Art. 12(5) GDPR. Mass automated submission with no individual authorization demonstrated. Single requester attempting bulk extraction of subscriber data. DPO documented reasoning and offered individual request path.",
      tasks: [
        {
          id: "media-dsar-5-task-1",
          dataAssetId: "media-asset-subscriber-db",
          assignee: "dpo",
          title: "Assess legitimacy of mass automated DSAR",
          description:
            "Review bulk DSAR for Art. 12(5) manifestly excessive/unfounded criteria. Check for individual authorization and legitimate basis.",
          status: "COMPLETED",
          completedAt: "2026-01-24T16:00:00Z",
          notes:
            "No individual authorizations attached. Email domain is a known DSAR automation service. Pattern consistent with data scraping attempts disguised as DSARs. Rejected under Art. 12(5).",
        },
      ],
      communications: [
        {
          id: "media-dsar-5-comm-1",
          direction: "OUTBOUND",
          channel: "email",
          subject: "Re: Automated Data Access Request (DSAR-HDM-2025-005) - Rejected",
          content:
            "We have reviewed your submission requesting data for 2,847 individuals. Under Article 12(5) GDPR, we are entitled to refuse requests that are manifestly excessive. This bulk automated request does not include individual authorizations and appears to be an attempt at mass data extraction. Each individual may submit their own request through our privacy portal.",
          sentAt: "2026-01-25T11:00:00Z",
          sentBy: "dpo",
        },
        {
          id: "media-dsar-5-comm-2",
          direction: "INBOUND",
          channel: "email",
          subject: "Re: Re: Automated Data Access Request (DSAR-HDM-2025-005) - Rejected",
          content:
            "We are a legitimate data rights management platform acting on behalf of data subjects. We will file a complaint with the relevant DPA.",
          sentAt: "2026-01-27T09:00:00Z",
        },
      ],
    },
  ],

  // ── Assessments ─────────────────────────────────────────────
  assessments: [
    // 1. LIA: Reader Analytics — APPROVED
    {
      id: "media-assess-reader-analytics-lia",
      templateType: "lia",
      activityId: "media-pa-reader-analytics",
      name: "Legitimate Interests Assessment: Reader Analytics & Engagement",
      description:
        "LIA assessing the use of Piano analytics for reader engagement tracking and paywall optimization under legitimate interests.",
      status: "APPROVED",
      riskLevel: "LOW",
      startedAt: "2025-09-15",
      submittedAt: "2025-10-01",
      completedAt: "2025-10-05",
      dueDate: "2025-11-15",
      responses: [],
      mitigations: [],
      approvals: [
        {
          id: "media-assess-lia1-approval-1",
          approver: "dpo",
          level: 1,
          status: "APPROVED",
          comments:
            "Legitimate interest in understanding reader behavior is clearly established. Pseudonymization and consent-gated advanced tracking provide adequate safeguards. Approved.",
          decidedAt: "2025-10-05",
        },
      ],
    },
    // 2. LIA: Podcast Analytics — IN_PROGRESS
    {
      id: "media-assess-podcast-analytics-lia",
      templateType: "lia",
      activityId: "media-pa-podcast-distribution",
      name: "Legitimate Interests Assessment: Podcast Analytics",
      description:
        "LIA for podcast listener analytics via Spotify for Podcasters. Assessing proportionality of geographic distribution tracking and listening behavior analysis.",
      status: "IN_PROGRESS",
      riskLevel: "LOW",
      startedAt: "2026-01-10",
      dueDate: "2026-03-10",
      responses: [],
      mitigations: [],
      approvals: [],
    },
    // 3. Custom: Comment Moderation Review — PENDING_REVIEW
    {
      id: "media-assess-comment-moderation",
      templateType: "custom",
      name: "Comment Moderation Privacy Review",
      description:
        "Review of the reader comments platform moderation practices, IP address retention, and user-generated content handling for GDPR compliance.",
      status: "PENDING_REVIEW",
      startedAt: "2025-12-01",
      submittedAt: "2026-01-15",
      dueDate: "2026-02-15",
      responses: [],
      mitigations: [],
      approvals: [
        {
          id: "media-assess-comment-approval-1",
          approver: "dpo",
          level: 1,
          status: "PENDING",
          comments: null,
        },
      ],
    },
    // 4. Custom: New Personalization Engine — DRAFT
    {
      id: "media-assess-personalization-engine",
      templateType: "custom",
      name: "Content Personalization Engine Assessment",
      description:
        "Privacy assessment for a proposed AI-driven content personalization engine that would use reading history and behavioral signals to recommend articles. Pre-launch review.",
      status: "DRAFT",
      startedAt: "2026-02-15",
      dueDate: "2026-04-15",
      responses: [],
      mitigations: [],
      approvals: [],
    },
    // 5. DPIA: Programmatic Advertising — APPROVED
    {
      id: "media-assess-programmatic-ads-dpia",
      templateType: "dpia",
      activityId: "media-pa-programmatic-ads",
      vendorId: "media-vendor-google-ad-manager",
      name: "DPIA: Programmatic Advertising & Real-Time Bidding",
      description:
        "Data Protection Impact Assessment for programmatic advertising via Google Ad Manager. Covers RTB data flows, TCF 2.2 consent propagation, reader behavioral profiling for ad targeting, and data sharing with demand-side platforms. Required due to large-scale profiling of 2M readers.",
      status: "APPROVED",
      riskLevel: "MEDIUM",
      riskScore: 52,
      startedAt: "2025-06-01",
      submittedAt: "2025-09-15",
      completedAt: "2025-10-01",
      dueDate: "2025-10-15",
      responses: [
        // S1: Processing Description
        {
          questionId: "q1_1",
          sectionId: "s1",
          response:
            "Categories processed: (1) Identifiers: IP addresses (truncated), device IDs, cookie IDs, advertising IDs; (2) Behavioral: reading history, article categories viewed, time-on-page, scroll depth, ad interaction data (impressions, clicks, viewability); (3) Location: coarse geographic location derived from IP (country/region level); (4) Consent records: TCF 2.2 consent strings, purpose-level consent status. No special category data is intentionally processed, though reading behavior on political or health articles could create inferred sensitive profiles.",
          responder: "dpo",
        },
        {
          questionId: "q1_2",
          sectionId: "s1",
          response:
            "Primary purpose: Revenue generation through targeted programmatic advertising to sustain Herald Digital's journalism operations. Programmatic advertising accounts for approximately 60% of total revenue. Secondary purpose: Providing relevant advertising experiences to readers who have consented to personalized ads. Non-consenting users are served contextual-only ads with no profiling.",
          responder: "dpo",
        },
        {
          questionId: "q1_3",
          sectionId: "s1",
          response: "Consent (Art. 6(1)(a))",
          responder: "dpo",
        },
        {
          questionId: "q1_4",
          sectionId: "s1",
          response: ["Customers", "Website visitors", "Members of the public"],
          responder: "dpo",
        },
        {
          questionId: "q1_5",
          sectionId: "s1",
          response: "> 1,000,000",
          responder: "dpo",
        },
        {
          questionId: "q1_6",
          sectionId: "s1",
          response:
            "Data flow: (1) Reader visits heralddigital.eu; (2) Didomi CMP collects TCF 2.2 consent; (3) If consent granted for Purpose 1 (Store/access device info) and Purpose 4 (Select personalised ads): reader behavioral signals and device identifiers are included in bid requests; (4) Google Ad Manager sends bid requests to registered DSPs (typically 20-50 per ad slot); (5) DSPs evaluate and respond with bids; (6) Winning ad served to reader; (7) Impression/click data recorded. Recipients: Google Ad Manager (ad server), registered DSPs (e.g., The Trade Desk, DV360, Amazon DSP), SSPs, data management platforms. All must be registered TCF 2.2 vendors.",
          responder: "admin",
        },
        // S2: Scope & Context
        {
          questionId: "q2_1",
          sectionId: "s2",
          response: "Mix of non-sensitive and sensitive indicators",
          responder: "dpo",
        },
        {
          questionId: "q2_2",
          sectionId: "s2",
          response:
            "Retention periods: (1) RTB bid request data: 30 days (ephemeral, used for frequency capping and fraud detection); (2) Ad interaction data (impressions/clicks): 90 days at individual level, then aggregated; (3) Consent records: 5 years (legal obligation to demonstrate consent); (4) Advertising IDs: refreshed every 13 months per TCF 2.2 requirements; (5) Aggregate reporting data: 2 years. Justification: Short retention for RTB data reflects data minimization principle. Longer retention for consent records supports accountability under Art. 5(2).",
          responder: "dpo",
        },
        {
          questionId: "q2_3",
          sectionId: "s2",
          response:
            "Primary processing: EU (Didomi CMP in France, Piano analytics in EU). International transfers: EU to US for Google Ad Manager (ad serving infrastructure). Transfer mechanism: EU SCCs (Module 1) with supplementary measures. Google participates in the EU-US Data Privacy Framework. DSPs receiving bid requests may process data globally but must be TCF 2.2 registered vendors with appropriate safeguards.",
          responder: "admin",
        },
        {
          questionId: "q2_4",
          sectionId: "s2",
          response: "Probably expected — a reasonable extension of the service",
          responder: "dpo",
        },
        // S3: Necessity & Proportionality
        {
          questionId: "q3_1",
          sectionId: "s3",
          response: "Highly beneficial — significantly more effective than alternatives",
          responder: "dpo",
        },
        {
          questionId: "q3_2",
          sectionId: "s3",
          response:
            "Alternatives considered: (1) Contextual-only advertising (no profiling): Implemented as fallback for non-consenting users but generates ~40% less revenue, threatening editorial sustainability; (2) Direct-sold advertising only: Insufficient scale — direct sales cover only ~25% of inventory; (3) Subscription-only model (no advertising): Current subscriber base of 150K insufficient to sustain operations; would require 4x growth. (4) First-party data only (no third-party cookies): Being explored as part of post-cookie strategy but current ecosystem still relies on third-party signals. The chosen approach (consent-based RTB) balances revenue needs with reader privacy by ensuring only consenting users are profiled.",
          responder: "dpo",
        },
        {
          questionId: "q3_3",
          sectionId: "s3",
          response:
            "Data minimization measures: (1) IP addresses truncated to /24 in bid requests; (2) Reading history categorized into IAB content taxonomy rather than sharing specific article URLs; (3) User IDs pseudonymized — no real names or emails in ad tech stack; (4) Bid request data TTL of 30 days; (5) Non-consenting users see zero profiling (contextual only); (6) Consent granularity: users can accept/reject individual TCF purposes; (7) Sensitive content categories (politics, health) excluded from behavioral targeting signals.",
          responder: "admin",
        },
        // S4: Consultation
        {
          questionId: "q4_1",
          sectionId: "s4",
          response: [
            "Data Protection Officer",
            "IT / Information Security",
            "Legal counsel",
            "Processor / vendor",
          ],
          responder: "dpo",
        },
        {
          questionId: "q4_2",
          sectionId: "s4",
          response:
            "Consultation outcomes: (1) DPO recommended excluding sensitive article categories from targeting signals — implemented; (2) IT Security recommended reducing bid request data TTL from 90 to 30 days — implemented; (3) Legal counsel advised on Art. 17(3)(a) journalism exemption boundaries for ad-related data — documented in policy; (4) Google Ad Manager team confirmed TCF 2.2 consent signal propagation to all downstream vendors; (5) External privacy counsel reviewed SCCs supplementary measures — approved with additional IP truncation requirement.",
          responder: "dpo",
        },
        // S5: Risk Identification
        {
          questionId: "q5_1",
          sectionId: "s5",
          response: true,
          responder: "dpo",
        },
        {
          questionId: "q5_2",
          sectionId: "s5",
          response: false,
          responder: "dpo",
        },
        {
          questionId: "q5_3",
          sectionId: "s5",
          response: false,
          responder: "dpo",
        },
        {
          questionId: "q5_4",
          sectionId: "s5",
          response: true,
          responder: "dpo",
        },
        {
          questionId: "q5_5",
          sectionId: "s5",
          response: false,
          responder: "dpo",
        },
        {
          questionId: "q5_6",
          sectionId: "s5",
          response:
            "Risk 1 — Consent Signal Failure: If Didomi CMP fails or consent strings are not properly propagated, readers may be profiled without valid consent. Likelihood: Possible. Severity: Severe. Risk 2 — Excessive Profiling via Reading Behavior: Reading patterns on political, health, or religious content could enable inference of special category data (political opinions, health conditions). Likelihood: Possible. Severity: Significant. Risk 3 — Data Leakage in RTB Bid Requests: Bid request data shared with DSPs may be used beyond the stated purpose or retained beyond permitted periods by bad actors in the supply chain. Likelihood: Possible. Severity: Significant. Risk 4 — Re-identification of Pseudonymized Readers: Combination of device identifiers, IP-derived location, and behavioral patterns could enable re-identification of individual readers. Likelihood: Remote. Severity: Significant. Risk 5 — Third-Country Access to Reader Data: US-based ad tech vendors subject to potential government surveillance requests (FISA 702). Likelihood: Remote. Severity: Severe.",
          responder: "dpo",
        },
        // S6: Mitigation Measures
        {
          questionId: "q6_1",
          sectionId: "s6",
          response: [
            "Encryption at rest",
            "Encryption in transit",
            "Pseudonymization",
            "Access controls / RBAC",
            "Audit logging",
            "Automated retention enforcement",
          ],
          responder: "admin",
        },
        {
          questionId: "q6_2",
          sectionId: "s6",
          response: [
            "Staff training / awareness",
            "Data processing agreements (DPAs)",
            "Privacy policies & procedures",
            "Regular audits / reviews",
            "Breach response plan",
            "Vendor management program",
          ],
          responder: "admin",
        },
        {
          questionId: "q6_3",
          sectionId: "s6",
          response:
            "Individual rights safeguards: (1) Didomi CMP provides granular consent controls — users can accept/reject each TCF purpose independently; (2) Consent can be withdrawn at any time via persistent privacy settings link in site footer; (3) Privacy notice clearly explains programmatic advertising in plain language with examples; (4) DSAR portal allows readers to request access to or deletion of ad-related data; (5) Contextual-only fallback for non-consenting users ensures no degradation of content access; (6) Ad preference center allows readers to view and modify their inferred interest categories; (7) Right to object to profiling honored immediately via CMP.",
          responder: "dpo",
        },
        // S7: Residual Risk & Conclusion
        {
          questionId: "q7_1",
          sectionId: "s7",
          response: "Medium",
          responder: "dpo",
        },
        {
          questionId: "q7_2",
          sectionId: "s7",
          response: "No — residual risk has been sufficiently mitigated",
          responder: "dpo",
        },
        {
          questionId: "q7_3",
          sectionId: "s7",
          response:
            "DPO recommendation: The programmatic advertising processing may proceed with the documented mitigations in place. Key conditions: (1) Quarterly consent signal propagation audits must continue; (2) Sensitive content category exclusion must be maintained and expanded as needed; (3) The transition to post-cookie advertising should be accelerated to reduce reliance on third-party identifiers; (4) Annual DPIA review required — next review date: October 2026. The residual risk of MEDIUM is acceptable given the revenue dependency and comprehensive consent infrastructure in place.",
          responder: "dpo",
        },
      ],
      mitigations: [
        {
          id: "media-assess-dpia-mit-1",
          riskId: "risk-consent-failure",
          title: "Consent Signal Propagation Monitoring",
          description:
            "Implement real-time monitoring of TCF 2.2 consent signal propagation from Didomi CMP to Google Ad Manager and downstream vendors. Alert on consent string mismatch or propagation failures.",
          status: "IMPLEMENTED",
          priority: 1,
          owner: "dpo",
          completedAt: "2025-08-15",
          evidence: "Monitoring dashboard deployed. Alert thresholds set at 99.5% propagation rate.",
        },
        {
          id: "media-assess-dpia-mit-2",
          riskId: "risk-excessive-profiling",
          title: "Sensitive Content Category Exclusion",
          description:
            "Exclude articles in sensitive IAB categories (politics, health, religion) from behavioral targeting signals. These articles use contextual-only ad serving regardless of consent status.",
          status: "IMPLEMENTED",
          priority: 1,
          owner: "admin",
          completedAt: "2025-07-20",
          evidence: "Category exclusion rules deployed in Google Ad Manager. Validated via test ad requests.",
        },
        {
          id: "media-assess-dpia-mit-3",
          riskId: "risk-bid-data-leakage",
          title: "Quarterly Supply Chain Audit",
          description:
            "Conduct quarterly audits of all registered DSPs and SSPs receiving bid requests. Verify TCF 2.2 compliance, data retention practices, and purpose limitation adherence.",
          status: "IMPLEMENTED",
          priority: 2,
          owner: "dpo",
          completedAt: "2025-09-01",
          evidence: "Q3 2025 audit completed. 3 non-compliant vendors removed from supply chain.",
        },
        {
          id: "media-assess-dpia-mit-4",
          riskId: "risk-reader-reidentification",
          title: "Enhanced Pseudonymization in Bid Requests",
          description:
            "Implement additional pseudonymization: rotate advertising IDs every 13 months, truncate IP to /24, and hash device fingerprint components before inclusion in bid requests.",
          status: "IMPLEMENTED",
          priority: 2,
          owner: "member2",
          completedAt: "2025-08-01",
          evidence: "Pseudonymization layer deployed. Validated that no PII leaks into bid request fields.",
        },
        {
          id: "media-assess-dpia-mit-5",
          riskId: "risk-third-country-access",
          title: "SCC Supplementary Measures for US Transfers",
          description:
            "Implement supplementary measures for EU-US data transfers: contractual restrictions on government access disclosure, data encryption with EU-held keys where feasible, regular TIA reviews.",
          status: "IMPLEMENTED",
          priority: 2,
          owner: "dpo",
          completedAt: "2025-07-01",
          evidence: "SCCs executed with Google. TIA documented. Annual review scheduled.",
        },
        {
          id: "media-assess-dpia-mit-6",
          riskId: "risk-consent-failure",
          title: "Contextual Advertising Fallback",
          description:
            "Ensure robust contextual-only advertising fallback for: (a) users who decline consent, (b) consent signal propagation failures, (c) CMP downtime. No profiling occurs in fallback mode.",
          status: "VERIFIED",
          priority: 1,
          owner: "admin",
          completedAt: "2025-09-10",
          evidence: "Fallback tested via CMP kill-switch simulation. Contextual ads served correctly with zero profiling.",
          dueDate: "2025-09-15",
        },
      ],
      approvals: [
        {
          id: "media-assess-dpia-approval-1",
          approver: "dpo",
          level: 1,
          status: "APPROVED",
          comments:
            "DPIA demonstrates adequate assessment of risks from programmatic advertising. Mitigations are comprehensive: consent signal monitoring, sensitive category exclusion, and supply chain audits address the primary risks. Residual MEDIUM risk is acceptable given the economic necessity and consent-based legal framework. Approved with condition of annual review.",
          decidedAt: "2025-09-25",
        },
        {
          id: "media-assess-dpia-approval-2",
          approver: "owner",
          level: 2,
          status: "APPROVED",
          comments:
            "Management sign-off: Programmatic advertising is critical to editorial sustainability. Privacy safeguards are proportionate. Approved.",
          decidedAt: "2025-10-01",
        },
      ],
    },
  ],

  // ── Incidents ───────────────────────────────────────────────
  incidents: [
    {
      id: "media-incident-consent-misconfig",
      publicId: "INC-HDM-2025-001",
      title: "Ad Tracker Firing Before Consent (Didomi Misconfiguration)",
      description:
        "During a CMS theme update, a Google Ad Manager tag was accidentally moved above the Didomi CMP initialization script, causing ad tracking pixels to fire before consent was collected. Affected approximately 45,000 page views over a 6-hour window before the issue was detected by automated consent monitoring.",
      type: "DATA_BREACH",
      severity: "MEDIUM",
      status: "CLOSED",
      discoveredAt: "2025-07-12T14:30:00Z",
      discoveredBy: "dpo",
      discoveryMethod: "Automated consent propagation monitoring alert",
      affectedRecords: 45000,
      affectedSubjects: ["Website visitors"],
      dataCategories: ["IDENTIFIERS", "BEHAVIORAL"],
      containedAt: "2025-07-12T16:00:00Z",
      containmentActions:
        "Reverted CMS theme update to previous version. Confirmed Didomi CMP loading before all ad tech scripts. Invalidated consent-less tracking data in Google Ad Manager.",
      rootCause: "CMS theme update moved ad tag placement above CMP script initialization",
      rootCauseCategory: "Configuration Error",
      resolvedAt: "2025-07-15T10:00:00Z",
      resolutionNotes:
        "Root cause fixed. Deployed automated pre-publish check that validates CMP loads before any tracking scripts. Affected tracking data purged from Google Ad Manager. DPA notification not required — no special category data, limited identifiers (device IDs only), and short exposure window.",
      lessonsLearned:
        "CMS deployment pipeline must include automated consent-before-tracking validation. Added to CI/CD pipeline. Editorial team briefed on privacy implications of theme changes.",
      notificationRequired: false,
      timeline: [
        {
          id: "media-incident-1-tl-1",
          timestamp: "2025-07-12T14:30:00Z",
          title: "Automated monitoring alert triggered",
          description: "Consent propagation monitoring detected ad tracking events without corresponding consent signals.",
          entryType: "detection",
          createdBy: "dpo",
        },
        {
          id: "media-incident-1-tl-2",
          timestamp: "2025-07-12T15:00:00Z",
          title: "Root cause identified",
          description: "Investigation traced issue to CMS theme update that reordered script loading. Ad tag firing before CMP initialization.",
          entryType: "investigation",
          createdBy: "admin",
        },
        {
          id: "media-incident-1-tl-3",
          timestamp: "2025-07-12T16:00:00Z",
          title: "Theme update reverted",
          description: "CMS theme rolled back to previous version. CMP now loading before ad tags. Issue contained.",
          entryType: "containment",
          createdBy: "admin",
        },
        {
          id: "media-incident-1-tl-4",
          timestamp: "2025-07-15T10:00:00Z",
          title: "Incident closed with preventive measures",
          description: "Automated pre-publish consent validation deployed. Tracking data purged. DPA notification assessed as not required.",
          entryType: "resolution",
          createdBy: "dpo",
        },
      ],
      tasks: [
        {
          id: "media-incident-1-task-1",
          assignee: "admin",
          title: "Revert CMS theme update",
          priority: "URGENT",
          status: "COMPLETED",
          completedAt: "2025-07-12T16:00:00Z",
          dueDate: "2025-07-12T17:00:00Z",
          notes: "Theme reverted via WordPress VIP deployment rollback.",
        },
        {
          id: "media-incident-1-task-2",
          assignee: "member2",
          title: "Purge consent-less tracking data from Google Ad Manager",
          priority: "HIGH",
          status: "COMPLETED",
          completedAt: "2025-07-14T11:00:00Z",
          dueDate: "2025-07-15T00:00:00Z",
          notes: "Google Ad Manager support confirmed deletion of 6-hour window tracking data.",
        },
        {
          id: "media-incident-1-task-3",
          assignee: "admin",
          title: "Deploy automated consent-before-tracking CI check",
          priority: "HIGH",
          status: "COMPLETED",
          completedAt: "2025-07-18T16:00:00Z",
          dueDate: "2025-07-20T00:00:00Z",
          notes: "CI pipeline check validates CMP script precedes all tracking scripts in page HTML.",
        },
      ],
      affectedAssets: [
        {
          id: "media-incident-1-aa-1",
          dataAssetId: "media-asset-ad-platform",
          impactLevel: "MEDIUM",
          compromised: false,
          notes: "Ad tracking fired without consent for 6 hours. No data exfiltration — tracking data captured within normal Google Ad Manager processing.",
        },
        {
          id: "media-incident-1-aa-2",
          dataAssetId: "media-asset-consent-platform",
          impactLevel: "LOW",
          compromised: false,
          notes: "Didomi CMP functioned correctly but was loaded after ad tags due to script ordering.",
        },
      ],
      notifications: [],
    },
    {
      id: "media-incident-cached-api",
      publicId: "INC-HDM-2025-002",
      title: "Reader Data Exposed via Cached API Response",
      description:
        "A misconfigured CDN caching rule caused authenticated API responses from the subscriber profile endpoint to be cached and served to other users. Approximately 1,200 subscriber profiles (names, emails, reading preferences) were potentially exposed to other authenticated subscribers over a 48-hour period.",
      type: "DATA_BREACH",
      severity: "HIGH",
      status: "INVESTIGATING",
      discoveredAt: "2026-02-20T09:00:00Z",
      discoveredBy: "member1",
      discoveryMethod: "Subscriber complaint — saw another user's profile data after login",
      affectedRecords: 1200,
      affectedSubjects: ["Subscribers"],
      dataCategories: ["IDENTIFIERS", "BEHAVIORAL"],
      notificationRequired: true,
      notificationDeadline: "2026-02-23T09:00:00Z",
      timeline: [
        {
          id: "media-incident-2-tl-1",
          timestamp: "2026-02-20T09:00:00Z",
          title: "Subscriber reports seeing another user's data",
          description: "Subscriber contacts support reporting that after login, they briefly saw another subscriber's profile information.",
          entryType: "detection",
          createdBy: "member1",
        },
        {
          id: "media-incident-2-tl-2",
          timestamp: "2026-02-20T10:30:00Z",
          title: "CDN caching issue confirmed",
          description: "Engineering confirmed that CDN was caching authenticated API responses. Cache-Control headers missing on subscriber profile endpoint.",
          entryType: "investigation",
          createdBy: "admin",
        },
        {
          id: "media-incident-2-tl-3",
          timestamp: "2026-02-20T11:00:00Z",
          title: "CDN cache purged and caching rule corrected",
          description: "All cached subscriber API responses purged. Cache-Control: no-store added to all authenticated endpoints.",
          entryType: "containment",
          createdBy: "admin",
        },
        {
          id: "media-incident-2-tl-4",
          timestamp: "2026-02-21T09:00:00Z",
          title: "Impact assessment initiated",
          description: "Analyzing CDN access logs to determine exact number of affected subscribers and which profiles were exposed.",
          entryType: "investigation",
          createdBy: "dpo",
        },
      ],
      tasks: [
        {
          id: "media-incident-2-task-1",
          assignee: "admin",
          title: "Complete CDN log analysis for affected records",
          priority: "URGENT",
          status: "IN_PROGRESS",
          dueDate: "2026-02-22T18:00:00Z",
          notes: "Analyzing 48 hours of CDN access logs to identify all cached subscriber profile responses and who received them.",
        },
        {
          id: "media-incident-2-task-2",
          assignee: "dpo",
          title: "Assess DPA notification requirement",
          description: "Evaluate whether 72-hour DPA notification is required based on affected records and data categories.",
          priority: "URGENT",
          status: "IN_PROGRESS",
          dueDate: "2026-02-22T12:00:00Z",
          notes: "Likely requires DPA notification — subscriber PII (names, emails) exposed. Preparing draft notification.",
        },
        {
          id: "media-incident-2-task-3",
          assignee: "member1",
          title: "Prepare affected subscriber notification",
          priority: "HIGH",
          status: "TODO",
          dueDate: "2026-02-24T12:00:00Z",
          notes: "Draft individual notification for affected subscribers once impact assessment is complete.",
        },
        {
          id: "media-incident-2-task-4",
          assignee: "admin",
          title: "Audit all API endpoints for caching misconfigurations",
          priority: "HIGH",
          status: "TODO",
          dueDate: "2026-02-28T00:00:00Z",
        },
      ],
      affectedAssets: [
        {
          id: "media-incident-2-aa-1",
          dataAssetId: "media-asset-subscriber-db",
          impactLevel: "HIGH",
          compromised: true,
          notes: "Subscriber profile data (name, email, reading preferences) exposed via cached API responses.",
        },
      ],
      notifications: [
        {
          id: "media-incident-2-notif-1",
          jurisdictionCode: "GDPR",
          recipientType: "DPA",
          recipientName: "Swedish Authority for Privacy Protection (IMY)",
          status: "DRAFTED",
          deadline: "2026-02-23T09:00:00Z",
          content:
            "Preliminary notification: Personal data of approximately 1,200 subscribers may have been exposed due to a CDN caching misconfiguration. Data categories: names, email addresses, reading preferences. Cause: Missing Cache-Control headers on authenticated API endpoint. Containment: CDN cache purged and headers corrected. Full impact assessment in progress.",
          notes: "72-hour deadline. Draft prepared, pending final impact numbers from CDN log analysis.",
        },
      ],
    },
    {
      id: "media-incident-mailchimp-export",
      publicId: "INC-HDM-2025-003",
      title: "Unauthorized Mailchimp List Export by Former Employee",
      description:
        "A former marketing team member whose Mailchimp access was not revoked upon departure exported the full newsletter subscriber list (82,000 records) two weeks after their last day. Detected during routine access audit.",
      type: "INSIDER_THREAT",
      severity: "MEDIUM",
      status: "CONTAINED",
      discoveredAt: "2025-11-05T11:00:00Z",
      discoveredBy: "admin",
      discoveryMethod: "Quarterly access rights review identified active account for departed employee",
      affectedRecords: 82000,
      affectedSubjects: ["Newsletter subscribers"],
      dataCategories: ["IDENTIFIERS"],
      containedAt: "2025-11-05T12:00:00Z",
      containmentActions:
        "Former employee's Mailchimp access immediately revoked. All Mailchimp API keys rotated. Export download link expired (7-day Mailchimp default). Legal team contacted former employee regarding data destruction obligation.",
      notificationRequired: true,
      notificationDeadline: "2025-11-08T11:00:00Z",
      timeline: [
        {
          id: "media-incident-3-tl-1",
          timestamp: "2025-11-05T11:00:00Z",
          title: "Quarterly access review detects anomaly",
          description: "Access rights audit found active Mailchimp account for employee who departed on 2025-10-20. Audit log shows list export on 2025-10-22.",
          entryType: "detection",
          createdBy: "admin",
        },
        {
          id: "media-incident-3-tl-2",
          timestamp: "2025-11-05T12:00:00Z",
          title: "Access revoked and API keys rotated",
          description: "Former employee's Mailchimp access revoked. API keys regenerated. Export link confirmed expired.",
          entryType: "containment",
          createdBy: "admin",
        },
        {
          id: "media-incident-3-tl-3",
          timestamp: "2025-11-06T10:00:00Z",
          title: "Legal team contacts former employee",
          description: "Legal sent formal data destruction notice requiring confirmation that exported data has been deleted.",
          entryType: "investigation",
          createdBy: "dpo",
        },
      ],
      tasks: [
        {
          id: "media-incident-3-task-1",
          assignee: "admin",
          title: "Revoke all platform access for former employee",
          priority: "URGENT",
          status: "COMPLETED",
          completedAt: "2025-11-05T12:00:00Z",
          dueDate: "2025-11-05T13:00:00Z",
          notes: "Mailchimp, HubSpot, and all other tool access revoked. Cross-checked with IT offboarding checklist.",
        },
        {
          id: "media-incident-3-task-2",
          assignee: "dpo",
          title: "Obtain data destruction confirmation from former employee",
          priority: "HIGH",
          status: "IN_PROGRESS",
          dueDate: "2025-11-15T00:00:00Z",
          notes: "Legal letter sent. Former employee acknowledged receipt but has not yet confirmed destruction.",
        },
        {
          id: "media-incident-3-task-3",
          assignee: "admin",
          title: "Improve offboarding access revocation process",
          priority: "MEDIUM",
          status: "IN_PROGRESS",
          dueDate: "2025-12-01T00:00:00Z",
          notes: "Working with IT to implement automated SaaS access revocation on employment termination date.",
        },
      ],
      affectedAssets: [
        {
          id: "media-incident-3-aa-1",
          dataAssetId: "media-asset-email-platform",
          impactLevel: "HIGH",
          compromised: true,
          notes: "Full newsletter subscriber list (82K records: names and email addresses) exported by former employee.",
        },
      ],
      notifications: [
        {
          id: "media-incident-3-notif-1",
          jurisdictionCode: "GDPR",
          recipientType: "DPA",
          recipientName: "Swedish Authority for Privacy Protection (IMY)",
          status: "SENT",
          deadline: "2025-11-08T11:00:00Z",
          content:
            "Notification: Personal data of 82,000 newsletter subscribers (names and email addresses) exported by a former employee whose access was not timely revoked. Containment measures taken. Data destruction requested from former employee.",
          notes: "Notification sent within 72 hours. IMY acknowledged receipt.",
        },
      ],
    },
    {
      id: "media-incident-ddos",
      publicId: "INC-HDM-2025-004",
      title: "DDoS Attack on Publishing Infrastructure",
      description:
        "Volumetric DDoS attack targeting heralddigital.eu during a major breaking news event. Peak traffic reached 15 Gbps. Site was intermittently unavailable for 2 hours. No personal data compromised — attack targeted availability only.",
      type: "SYSTEM_COMPROMISE",
      severity: "LOW",
      status: "CLOSED",
      discoveredAt: "2025-09-20T18:00:00Z",
      discoveredBy: "admin",
      discoveryMethod: "CDN/WAF automated DDoS detection alert",
      affectedRecords: 0,
      affectedSubjects: ["Website visitors"],
      dataCategories: [],
      containedAt: "2025-09-20T19:30:00Z",
      containmentActions:
        "Cloudflare DDoS protection activated (Under Attack mode). Rate limiting applied. Attack traffic mitigated at edge.",
      rootCause: "Volumetric DDoS attack, likely motivated by breaking news content",
      rootCauseCategory: "External Attack",
      resolvedAt: "2025-09-21T08:00:00Z",
      resolutionNotes:
        "Attack subsided after 4 hours. Enhanced DDoS protection rules deployed. No personal data impact — availability-only incident. DPA notification not required.",
      lessonsLearned:
        "Auto-escalation to DDoS mitigation was delayed by 30 minutes. Updated Cloudflare rules to auto-activate Under Attack mode at lower thresholds during high-traffic news events.",
      notificationRequired: false,
      timeline: [
        {
          id: "media-incident-4-tl-1",
          timestamp: "2025-09-20T18:00:00Z",
          title: "DDoS attack detected",
          description: "Cloudflare WAF detected abnormal traffic spike (15 Gbps). Site availability degraded.",
          entryType: "detection",
          createdBy: "admin",
        },
        {
          id: "media-incident-4-tl-2",
          timestamp: "2025-09-20T18:30:00Z",
          title: "Under Attack mode activated",
          description: "Cloudflare Under Attack mode enabled. JavaScript challenge applied to all visitors.",
          entryType: "containment",
          createdBy: "admin",
        },
        {
          id: "media-incident-4-tl-3",
          timestamp: "2025-09-20T19:30:00Z",
          title: "Attack mitigated, site restored",
          description: "DDoS traffic filtered at edge. Site fully accessible. Monitoring continues.",
          entryType: "containment",
          createdBy: "admin",
        },
        {
          id: "media-incident-4-tl-4",
          timestamp: "2025-09-21T08:00:00Z",
          title: "Incident closed",
          description: "Attack fully subsided. No data breach. Enhanced DDoS rules deployed. Incident closed.",
          entryType: "resolution",
          createdBy: "dpo",
        },
      ],
      tasks: [
        {
          id: "media-incident-4-task-1",
          assignee: "admin",
          title: "Activate Cloudflare Under Attack mode",
          priority: "URGENT",
          status: "COMPLETED",
          completedAt: "2025-09-20T18:30:00Z",
          dueDate: "2025-09-20T18:30:00Z",
        },
        {
          id: "media-incident-4-task-2",
          assignee: "admin",
          title: "Deploy enhanced DDoS mitigation rules",
          priority: "HIGH",
          status: "COMPLETED",
          completedAt: "2025-09-22T14:00:00Z",
          dueDate: "2025-09-25T00:00:00Z",
          notes: "Lower auto-escalation thresholds configured. Breaking news traffic pattern rules added.",
        },
      ],
      affectedAssets: [
        {
          id: "media-incident-4-aa-1",
          dataAssetId: "media-asset-cms",
          impactLevel: "MEDIUM",
          compromised: false,
          notes: "Site availability impacted for 2 hours. No data compromise.",
        },
      ],
      notifications: [],
    },
  ],

  // ── Audit Logs ──────────────────────────────────────────────
  auditLogs: [
    {
      id: "media-audit-01",
      user: "owner",
      entityType: "Organization",
      entityId: "media-organization",
      action: "CREATE",
      changes: { name: "Herald Digital Media", slug: "demo-media" },
      createdAt: "2024-01-01T09:00:00Z",
    },
    {
      id: "media-audit-02",
      user: "dpo",
      entityType: "DataAsset",
      entityId: "media-asset-subscriber-db",
      action: "CREATE",
      changes: { name: "Subscriber Database", type: "DATABASE" },
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "media-audit-03",
      user: "dpo",
      entityType: "DataAsset",
      entityId: "media-asset-ad-platform",
      action: "CREATE",
      changes: { name: "Programmatic Advertising (Google Ad Manager)", type: "THIRD_PARTY" },
      createdAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "media-audit-04",
      user: "dpo",
      entityType: "ProcessingActivity",
      entityId: "media-pa-programmatic-ads",
      action: "CREATE",
      changes: { name: "Programmatic Advertising & Real-Time Bidding", legalBasis: "CONSENT" },
      createdAt: "2024-02-01T09:00:00Z",
    },
    {
      id: "media-audit-05",
      user: "dpo",
      entityType: "Vendor",
      entityId: "media-vendor-google-ad-manager",
      action: "CREATE",
      changes: { name: "Google Ad Manager", riskTier: "HIGH" },
      createdAt: "2024-02-15T11:00:00Z",
    },
    {
      id: "media-audit-06",
      user: "dpo",
      entityType: "Vendor",
      entityId: "media-vendor-didomi",
      action: "CREATE",
      changes: { name: "Didomi", riskTier: "LOW" },
      createdAt: "2024-02-15T11:30:00Z",
    },
    {
      id: "media-audit-07",
      user: "dpo",
      entityType: "Assessment",
      entityId: "media-assess-programmatic-ads-dpia",
      action: "CREATE",
      changes: { name: "DPIA: Programmatic Advertising & Real-Time Bidding", templateType: "dpia" },
      createdAt: "2025-06-01T09:00:00Z",
    },
    {
      id: "media-audit-08",
      user: "dpo",
      entityType: "Assessment",
      entityId: "media-assess-programmatic-ads-dpia",
      action: "UPDATE",
      changes: { status: { from: "DRAFT", to: "IN_PROGRESS" } },
      createdAt: "2025-06-15T10:00:00Z",
    },
    {
      id: "media-audit-09",
      user: "admin",
      entityType: "Assessment",
      entityId: "media-assess-programmatic-ads-dpia",
      action: "UPDATE",
      changes: { status: { from: "IN_PROGRESS", to: "PENDING_REVIEW" } },
      createdAt: "2025-09-15T14:00:00Z",
    },
    {
      id: "media-audit-10",
      user: "dpo",
      entityType: "Assessment",
      entityId: "media-assess-programmatic-ads-dpia",
      action: "APPROVE",
      changes: { status: { from: "PENDING_REVIEW", to: "APPROVED" }, riskLevel: "MEDIUM", riskScore: 52 },
      createdAt: "2025-10-01T10:00:00Z",
    },
    {
      id: "media-audit-11",
      user: "dpo",
      entityType: "Incident",
      entityId: "media-incident-consent-misconfig",
      action: "CREATE",
      changes: { title: "Ad Tracker Firing Before Consent (Didomi Misconfiguration)", severity: "MEDIUM" },
      createdAt: "2025-07-12T14:30:00Z",
    },
    {
      id: "media-audit-12",
      user: "admin",
      entityType: "Incident",
      entityId: "media-incident-consent-misconfig",
      action: "UPDATE",
      changes: { status: { from: "INVESTIGATING", to: "CONTAINED" } },
      createdAt: "2025-07-12T16:00:00Z",
    },
    {
      id: "media-audit-13",
      user: "dpo",
      entityType: "Incident",
      entityId: "media-incident-consent-misconfig",
      action: "UPDATE",
      changes: { status: { from: "CONTAINED", to: "CLOSED" } },
      createdAt: "2025-07-15T10:00:00Z",
    },
    {
      id: "media-audit-14",
      user: "dpo",
      entityType: "DSARRequest",
      entityId: "media-dsar-1",
      action: "CREATE",
      changes: { type: "ACCESS", requesterName: "Annika Lindgren" },
      createdAt: "2025-09-15T10:30:00Z",
    },
    {
      id: "media-audit-15",
      user: "dpo",
      entityType: "DSARRequest",
      entityId: "media-dsar-1",
      action: "UPDATE",
      changes: { status: { from: "IN_PROGRESS", to: "COMPLETED" } },
      createdAt: "2025-10-08T14:20:00Z",
    },
    {
      id: "media-audit-16",
      user: "dpo",
      entityType: "DSARRequest",
      entityId: "media-dsar-5",
      action: "REJECT",
      changes: { status: { from: "SUBMITTED", to: "REJECTED" }, reason: "Manifestly excessive (Art. 12(5))" },
      createdAt: "2026-01-25T11:00:00Z",
    },
    {
      id: "media-audit-17",
      user: "admin",
      entityType: "Incident",
      entityId: "media-incident-mailchimp-export",
      action: "CREATE",
      changes: { title: "Unauthorized Mailchimp List Export by Former Employee", severity: "MEDIUM" },
      createdAt: "2025-11-05T11:00:00Z",
    },
    {
      id: "media-audit-18",
      user: "dpo",
      entityType: "Incident",
      entityId: "media-incident-cached-api",
      action: "CREATE",
      changes: { title: "Reader Data Exposed via Cached API Response", severity: "HIGH" },
      createdAt: "2026-02-20T09:00:00Z",
    },
    {
      id: "media-audit-19",
      user: "dpo",
      entityType: "Assessment",
      entityId: "media-assess-reader-analytics-lia",
      action: "APPROVE",
      changes: { status: { from: "PENDING_REVIEW", to: "APPROVED" } },
      createdAt: "2025-10-05T10:00:00Z",
    },
    {
      id: "media-audit-20",
      user: "dpo",
      entityType: "DataTransfer",
      entityId: "media-transfer-google-rtb",
      action: "CREATE",
      changes: { name: "EU to US: Google Ad Manager (RTB)", mechanism: "STANDARD_CONTRACTUAL_CLAUSES" },
      createdAt: "2025-06-15T09:00:00Z",
    },
  ],
};
