import React from "react";
import path from "path";
import { Image, View } from "@react-pdf/renderer";
import { Graphviz } from "@hpcc-js/wasm-graphviz";
import { Resvg } from "@resvg/resvg-js";

/**
 * Server-side data flow graph renderer for PDF reports.
 *
 * Pipeline:
 *   1. buildDotSource: turns assets+flows into a Graphviz DOT string with
 *      colors, clusters, and edge labels.
 *   2. renderFlowGraphPng: runs Graphviz (WASM) → SVG, then resvg → PNG,
 *      and returns a base64 data URI ready to embed in @react-pdf.
 *   3. <FlowGraphImage>: a React component that takes the pre-rendered
 *      data URI and dimensions and emits an @react-pdf <Image>.
 *
 * The render is async, so consumers must call renderFlowGraphPng in their
 * route handler before invoking renderToBuffer on the React tree.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PdfFlowAsset {
  id: string;
  name: string;
  type: string;
}

export interface PdfFlowEdge {
  sourceAssetId: string;
  destinationAssetId: string;
  /** Optional human label shown on the edge (e.g., "IDENTIFIERS · Daily") */
  label?: string;
  /** Auto-generated edges are drawn dashed and lighter to de-emphasize them */
  isAutoGenerated?: boolean;
}

export interface PdfFlowCluster {
  id: string;
  label: string;
  /** Subset of asset ids in this cluster (each id must also exist in `assets`) */
  assetIds: string[];
}

export interface BuildDotOptions {
  /** Optional graph title (rendered as `labelloc="t"`) */
  title?: string;
  /** When set, group assets into bordered subgraphs (used by ROPA) */
  clusters?: PdfFlowCluster[];
  /** Layout direction. LR is the default; TB works better for tall lists. */
  rankdir?: "LR" | "TB";
}

// ---------------------------------------------------------------------------
// Color palette — keyed by DataAssetType. Anchored on the brand teal.
// ---------------------------------------------------------------------------

const TYPE_COLORS: Record<string, { fill: string; border: string; text: string }> = {
  APPLICATION:   { fill: "#cce8f1", border: "#1f6f8c", text: "#0c3845" }, // brand teal-100
  CLOUD_SERVICE: { fill: "#dbeafe", border: "#1e40af", text: "#1e3a8a" }, // sky
  DATABASE:      { fill: "#e0e7ff", border: "#3730a3", text: "#312e81" }, // indigo
  FILE_SYSTEM:   { fill: "#f3f4f6", border: "#4b5563", text: "#1f2937" }, // gray
  THIRD_PARTY:   { fill: "#fef3c7", border: "#92400e", text: "#78350f" }, // amber
  PHYSICAL:      { fill: "#e7e5e4", border: "#57534e", text: "#292524" }, // stone
  OTHER:         { fill: "#f1f5f9", border: "#475569", text: "#0f172a" }, // slate
};

function colorFor(type: string) {
  return TYPE_COLORS[type] ?? TYPE_COLORS.OTHER!;
}

// ---------------------------------------------------------------------------
// DOT generation
// ---------------------------------------------------------------------------

/** Escape a string for inclusion inside a DOT double-quoted string. */
function dotEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Escape a string for inclusion inside a DOT HTML-like label. */
function htmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function nodeId(id: string): string {
  // Sanitize: DOT allows IDs to be any double-quoted string, but we wrap in quotes
  return `"${dotEscape(id)}"`;
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}

function typeDisplay(t: string): string {
  return t.replace(/_/g, " ").toLowerCase();
}

export function buildDotSource(
  assets: PdfFlowAsset[],
  edges: PdfFlowEdge[],
  options: BuildDotOptions = {}
): string {
  const { title, clusters, rankdir = "LR" } = options;

  // Restrict to assets that participate in at least one flow OR appear in a cluster
  const usedIds = new Set<string>();
  for (const e of edges) {
    usedIds.add(e.sourceAssetId);
    usedIds.add(e.destinationAssetId);
  }
  for (const c of clusters ?? []) {
    for (const id of c.assetIds) usedIds.add(id);
  }
  const assetMap = new Map(assets.map((a) => [a.id, a]));
  const usedAssets = assets.filter((a) => usedIds.has(a.id));

  if (usedAssets.length === 0) return "";

  const lines: string[] = [];
  lines.push(`digraph G {`);
  lines.push(`  graph [rankdir="${rankdir}", bgcolor="white", fontname="Noto Sans", nodesep=0.45, ranksep=0.7, splines="true", pad=0.25];`);
  lines.push(`  node  [shape=box, style="rounded,filled", fontname="Noto Sans", fontsize=11, penwidth=1, margin="0.18,0.10"];`);
  lines.push(`  edge  [fontname="Noto Sans", fontsize=8, color="#4b5563", penwidth=1.1, arrowsize=0.7];`);
  if (title) {
    lines.push(`  labelloc="t"; label=<<font face="Noto Sans" point-size="13"><b>${htmlEscape(title)}</b></font>>;`);
  }

  // Render each node — either inside a cluster or at the top level
  const inClusterIds = new Set<string>();
  for (const c of clusters ?? []) {
    for (const id of c.assetIds) inClusterIds.add(id);
  }

  function renderNode(asset: PdfFlowAsset, indent: string): string {
    const c = colorFor(asset.type);
    const name = htmlEscape(truncate(asset.name, 36));
    const type = htmlEscape(truncate(typeDisplay(asset.type), 24));
    const label = `<<font color="${c.text}" point-size="11"><b>${name}</b></font><br/><font color="${c.text}" point-size="8">${type}</font>>`;
    return `${indent}${nodeId(asset.id)} [label=${label}, fillcolor="${c.fill}", color="${c.border}"];`;
  }

  // Clusters first
  for (const c of clusters ?? []) {
    const clusterAssets = c.assetIds
      .map((id) => assetMap.get(id))
      .filter((a): a is PdfFlowAsset => !!a);
    if (clusterAssets.length === 0) continue;

    lines.push(`  subgraph "cluster_${dotEscape(c.id)}" {`);
    lines.push(`    label=<<font face="Noto Sans" point-size="10" color="#4b5563"><b>${htmlEscape(c.label)}</b></font>>;`);
    lines.push(`    style="rounded,dashed"; color="#9ca3af"; bgcolor="#f9fafb"; margin=10;`);
    for (const a of clusterAssets) {
      lines.push(renderNode(a, "    "));
    }
    lines.push(`  }`);
  }

  // Top-level nodes (those not in any cluster)
  for (const a of usedAssets) {
    if (inClusterIds.has(a.id)) continue;
    lines.push(renderNode(a, "  "));
  }

  // Edges
  for (const e of edges) {
    if (!assetMap.has(e.sourceAssetId) || !assetMap.has(e.destinationAssetId)) continue;
    const attrs: string[] = [];
    if (e.label) {
      attrs.push(`label=<<font color="#6b7280" point-size="8">${htmlEscape(e.label)}</font>>`);
    }
    if (e.isAutoGenerated) {
      attrs.push(`style="dashed"`);
      attrs.push(`color="#9ca3af"`);
      attrs.push(`penwidth=0.7`);
    }
    const attrStr = attrs.length > 0 ? ` [${attrs.join(", ")}]` : "";
    lines.push(`  ${nodeId(e.sourceAssetId)} -> ${nodeId(e.destinationAssetId)}${attrStr};`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Render pipeline
// ---------------------------------------------------------------------------

// Cache the Graphviz WASM instance across requests within the same warm
// function — load() is the expensive part.
let graphvizPromise: Promise<Graphviz> | null = null;
function getGraphviz(): Promise<Graphviz> {
  if (!graphvizPromise) graphvizPromise = Graphviz.load();
  return graphvizPromise;
}

const FONT_PATH = path.join(process.cwd(), "src/server/services/export/fonts/NotoSans-Regular.ttf");

export interface RenderedFlowGraph {
  /** data:image/png;base64,... ready for <Image src={...}> */
  dataUri: string;
  /** PNG width in pixels (post-rasterization) */
  width: number;
  /** PNG height in pixels */
  height: number;
}

export interface RenderFlowGraphOptions extends BuildDotOptions {
  /** Target width in PDF points. The PNG is rendered at 2x for crispness. */
  fitWidth?: number;
}

/**
 * Render a flow graph to PNG and return a base64 data URI ready for
 * embedding in @react-pdf via <Image src={...}>.
 *
 * Returns null when there's nothing to draw (no flows + no clusters).
 */
export async function renderFlowGraphPng(
  assets: PdfFlowAsset[],
  edges: PdfFlowEdge[],
  options: RenderFlowGraphOptions = {}
): Promise<RenderedFlowGraph | null> {
  const dot = buildDotSource(assets, edges, options);
  if (!dot) return null;

  const graphviz = await getGraphviz();
  const svg = graphviz.dot(dot, "svg");

  const fitWidth = options.fitWidth ?? 720; // PDF points
  // Render at 2x for retina-grade PNG, then @react-pdf scales to fitWidth.
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: Math.round(fitWidth * 2) },
    font: {
      loadSystemFonts: false,
      fontFiles: [FONT_PATH],
      defaultFontFamily: "Noto Sans",
    },
    background: "white",
  });
  const rendered = resvg.render();
  const png = rendered.asPng();

  return {
    dataUri: `data:image/png;base64,${png.toString("base64")}`,
    width: rendered.width,
    height: rendered.height,
  };
}

// ---------------------------------------------------------------------------
// React component for embedding in PDF reports
// ---------------------------------------------------------------------------

interface FlowGraphImageProps {
  /** Output of renderFlowGraphPng. Pass null to render nothing. */
  graph: RenderedFlowGraph | null;
  /** Display width in PDF points. Defaults to the rendered fitWidth. */
  width?: number;
  /**
   * Max display height in PDF points. If the natural aspect-ratio render
   * would exceed this, the image is scaled down proportionally to fit on a
   * single page. A4 (842pt) minus page padding/header/footer → safe ~680pt.
   */
  maxHeight?: number;
}

export function FlowGraphImage({ graph, width, maxHeight = 680 }: FlowGraphImageProps) {
  if (!graph) return null;
  let displayWidth = width ?? graph.width / 2; // PNG is 2x DPI
  const aspect = graph.height / graph.width;
  let displayHeight = displayWidth * aspect;
  if (displayHeight > maxHeight) {
    displayHeight = maxHeight;
    displayWidth = displayHeight / aspect;
  }

  return (
    <View wrap={false}>
      {/* eslint-disable-next-line jsx-a11y/alt-text */}
      <Image src={graph.dataUri} style={{ width: displayWidth, height: displayHeight }} />
    </View>
  );
}
