"use client";

import { Filter, X, Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { SENSITIVITY_COLOR, type Sensitivity } from "./flow-palette";

export type SensitivityFilter = Sensitivity | "all";

export interface FlowFilters {
  sensitivity: SensitivityFilter;
  showAutoGenerated: boolean;
  categories: Set<string>;
}

export const DEFAULT_FILTERS: FlowFilters = {
  sensitivity: "all",
  showAutoGenerated: true,
  categories: new Set(),
};

const ALL_CATEGORIES: Array<{ key: string; label: string }> = [
  { key: "IDENTIFIERS", label: "Identifiers" },
  { key: "DEMOGRAPHICS", label: "Demographics" },
  { key: "FINANCIAL", label: "Financial" },
  { key: "HEALTH", label: "Health" },
  { key: "BIOMETRIC", label: "Biometric" },
  { key: "LOCATION", label: "Location" },
  { key: "BEHAVIORAL", label: "Behavioural" },
  { key: "EMPLOYMENT", label: "Employment" },
  { key: "EDUCATION", label: "Education" },
  { key: "POLITICAL", label: "Political" },
  { key: "RELIGIOUS", label: "Religious" },
  { key: "GENETIC", label: "Genetic" },
  { key: "SEXUAL_ORIENTATION", label: "Sexual orientation" },
  { key: "CRIMINAL", label: "Criminal" },
];

const SENSITIVITY_BUTTONS: Array<{
  key: SensitivityFilter;
  label: string;
  swatch?: string;
}> = [
  { key: "all", label: "All" },
  { key: "special", label: "Special cat.", swatch: SENSITIVITY_COLOR.special.stroke },
  { key: "sensitive", label: "Personal", swatch: SENSITIVITY_COLOR.sensitive.stroke },
  { key: "general", label: "General", swatch: SENSITIVITY_COLOR.general.stroke },
];

export function FlowFilterToolbar({
  filters,
  onChange,
  edgeCount,
  totalEdges,
}: {
  filters: FlowFilters;
  onChange: (next: FlowFilters) => void;
  edgeCount: number;
  totalEdges: number;
}) {
  const hasActiveFilters =
    filters.sensitivity !== "all" ||
    !filters.showAutoGenerated ||
    filters.categories.size > 0;

  return (
    <div
      className="flex items-center gap-2 shadow-sm px-2 py-1.5 text-xs"
      style={{
        backgroundColor: "#ffffff",
        border: "1px solid #e2e8f0",
        color: "#334155",
      }}
    >
      {/* Sensitivity filter pills */}
      <div className="flex items-center gap-1">
        {SENSITIVITY_BUTTONS.map((b) => {
          const active = filters.sensitivity === b.key;
          return (
            <button
              key={b.key}
              onClick={() => onChange({ ...filters, sensitivity: b.key })}
              className="flex items-center gap-1 px-2 py-1 font-semibold uppercase tracking-wider transition-colors"
              style={{
                fontSize: 10,
                letterSpacing: "0.06em",
                backgroundColor: active ? "#0f172a" : "#ffffff",
                color: active ? "#ffffff" : "#475569",
              }}
            >
              {b.swatch && (
                <span
                  className="inline-block w-2 h-2 shrink-0"
                  style={{ backgroundColor: b.swatch }}
                />
              )}
              {b.label}
            </button>
          );
        })}
      </div>

      <div className="w-px h-5" style={{ backgroundColor: "#e2e8f0" }} aria-hidden />

      {/* Auto-generated toggle */}
      <button
        onClick={() =>
          onChange({ ...filters, showAutoGenerated: !filters.showAutoGenerated })
        }
        className="flex items-center gap-1.5 px-2 py-1 font-semibold uppercase tracking-wider transition-colors hover:bg-slate-100"
        style={{ fontSize: 10, letterSpacing: "0.06em", color: "#475569" }}
        title={
          filters.showAutoGenerated
            ? "Hide auto-generated flows"
            : "Show auto-generated flows"
        }
      >
        {filters.showAutoGenerated ? (
          <Eye className="w-3 h-3" />
        ) : (
          <EyeOff className="w-3 h-3" />
        )}
        Auto-gen
      </button>

      <div className="w-px h-5" style={{ backgroundColor: "#e2e8f0" }} aria-hidden />

      {/* Category multi-select */}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs gap-1.5 px-2 uppercase tracking-wider font-semibold hover:bg-slate-100"
            style={{ letterSpacing: "0.06em", color: "#475569" }}
          >
            <Filter className="w-3 h-3" />
            Categories
            {filters.categories.size > 0 && (
              <span
                className="ml-1 inline-flex items-center justify-center min-w-4 h-4 px-1 text-[9px] font-bold"
                style={{ backgroundColor: "#0f172a", color: "#ffffff" }}
              >
                {filters.categories.size}
              </span>
            )}
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start" className="max-h-80 overflow-y-auto">
          {ALL_CATEGORIES.map((c) => (
            <DropdownMenuCheckboxItem
              key={c.key}
              checked={filters.categories.has(c.key)}
              onCheckedChange={(checked) => {
                const next = new Set(filters.categories);
                if (checked) next.add(c.key);
                else next.delete(c.key);
                onChange({ ...filters, categories: next });
              }}
            >
              {c.label}
            </DropdownMenuCheckboxItem>
          ))}
          {filters.categories.size > 0 && (
            <>
              <DropdownMenuSeparator />
              <button
                onClick={() => onChange({ ...filters, categories: new Set() })}
                className="w-full text-left px-2 py-1.5 text-xs hover:bg-slate-100"
                style={{ color: "#64748b" }}
              >
                Clear categories
              </button>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <div className="flex-1" />

      {/* Result counter + clear */}
      <span
        className="text-[10px] uppercase tracking-wider font-semibold"
        style={{ color: "#64748b" }}
      >
        {edgeCount} / {totalEdges} flows
      </span>

      {hasActiveFilters && (
        <button
          onClick={() => onChange(DEFAULT_FILTERS)}
          className="flex items-center gap-1 px-1.5 py-0.5 transition-colors hover:bg-slate-100"
          style={{ color: "#64748b" }}
          title="Clear all filters"
        >
          <X className="w-3 h-3" />
        </button>
      )}
    </div>
  );
}
