"use client";

import { memo } from "react";
import {
  BaseEdge,
  EdgeLabelRenderer,
  getBezierPath,
  type EdgeProps,
  type Edge,
} from "@xyflow/react";
import type { FlowEdgeData } from "./useDataFlowGraph";
import {
  classifyCategories,
  SENSITIVITY_COLOR,
  strokeWidthForFrequency,
  abbrevCategory,
} from "./flow-palette";

type FlowEdgeProps = EdgeProps<Edge<FlowEdgeData>>;

function FlowEdgeComponent({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
  selected,
}: FlowEdgeProps) {
  const isReturn = data?.isReturn ?? false;
  const isBidirectional = data?.isBidirectional ?? false;
  const isAutoGenerated = data?.isAutoGenerated ?? false;
  const isDimmed = data?.isDimmed ?? false;
  const flow = data?.flow;

  const sensitivity = classifyCategories(flow?.dataCategories);
  const sColor = SENSITIVITY_COLOR[sensitivity];

  const baseWidth = strokeWidthForFrequency(flow?.frequency);
  const strokeWidth = selected ? baseWidth + 1.5 : baseWidth;

  const curvature = isReturn ? 0.5 : isBidirectional ? -0.5 : 0.22;

  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
    curvature,
  });

  // Dim rules — explicit (dim flag) beats everything; auto-generated is always subtle.
  const opacity = isDimmed ? 0.12 : selected ? 1 : isAutoGenerated ? 0.55 : 0.85;

  // Short label: show abbreviated top category + frequency; or name if just one category
  const categoryLabel =
    flow?.dataCategories && flow.dataCategories.length > 0
      ? flow.dataCategories.length === 1
        ? abbrevCategory(flow.dataCategories[0]!)
        : `${abbrevCategory(flow.dataCategories[0]!)} +${flow.dataCategories.length - 1}`
      : null;
  const freqLabel = flow?.frequency ? ` · ${flow.frequency.toLowerCase()}` : "";
  const label = categoryLabel ? `${categoryLabel}${freqLabel}` : flow?.name || "Flow";

  return (
    <>
      <BaseEdge
        id={id}
        path={edgePath}
        style={{
          stroke: sColor.stroke,
          strokeWidth,
          strokeDasharray: isAutoGenerated ? "4 3" : undefined,
          opacity,
          transition: "opacity 200ms, stroke-width 150ms",
        }}
        markerEnd={`url(#arrowhead-${sensitivity})`}
      />
      <EdgeLabelRenderer>
        <div
          className="absolute flex items-center gap-1 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider cursor-pointer transition-all duration-200"
          style={{
            transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
            pointerEvents: "all",
            opacity: isDimmed ? 0.15 : 1,
            backgroundColor: selected ? sColor.stroke : "#ffffff",
            color: selected ? "white" : sColor.fg,
            border: `1px solid ${selected ? sColor.stroke : sColor.bg}`,
            letterSpacing: "0.04em",
          }}
        >
          {label}
        </div>
      </EdgeLabelRenderer>
    </>
  );
}

export const FlowEdge = memo(FlowEdgeComponent);
