"use client";

import { useMemo, useState, useEffect } from "react";
import type { Node, Edge } from "@xyflow/react";
import type { DataAssetType } from "@prisma/client";
import ELK from "elkjs/lib/elk.bundled.js";
import { classifyCategories } from "./flow-palette";

const elk = new ELK();

export interface FlowData {
  id: string;
  name: string;
  description?: string | null;
  sourceAssetId: string;
  destinationAssetId: string;
  dataCategories: string[];
  frequency?: string | null;
  volume?: string | null;
  encryptionMethod?: string | null;
  isAutomated: boolean;
  metadata?: unknown;
  sourceAsset: AssetData;
  destinationAsset: AssetData;
}

export interface AssetData {
  id: string;
  name: string;
  description?: string | null;
  type: DataAssetType;
  owner?: string | null;
  location?: string | null;
  hostingType?: string | null;
  vendor?: string | null;
  isProduction: boolean;
}

export interface AssetNodeData extends Record<string, unknown> {
  label: string;
  asset: AssetData;
  incomingFlows: number;
  outgoingFlows: number;
  /** Top N distinct data categories across all this asset's flows. */
  topCategories: string[];
  /** Highest-sensitivity class across this asset's flows. Drives the risk halo. */
  peakSensitivity: "special" | "sensitive" | "general" | "none";
  isHighlighted?: boolean;
  isDimmed?: boolean;
  isFocused?: boolean;
}

export interface FlowEdgeData extends Record<string, unknown> {
  flow: FlowData;
  label: string;
  isBidirectional: boolean;
  isReturn: boolean;
  isAutoGenerated: boolean;
  isDimmed?: boolean;
}

export type AssetNode = Node<AssetNodeData>;
export type FlowEdge = Edge<FlowEdgeData>;

const NODE_WIDTH = 240;
const NODE_HEIGHT = 120;

async function getLayoutedElements(
  nodes: AssetNode[],
  edges: FlowEdge[],
  direction: "LR" | "TB" = "LR"
): Promise<{ nodes: AssetNode[]; edges: FlowEdge[] }> {
  const elkDirection = direction === "LR" ? "RIGHT" : "DOWN";

  const graph = {
    id: "root",
    layoutOptions: {
      "elk.algorithm": "layered",
      "elk.direction": elkDirection,
      "elk.spacing.nodeNode": "60",
      "elk.layered.spacing.nodeNodeBetweenLayers": "120",
      "elk.layered.spacing.edgeNodeBetweenLayers": "40",
      "elk.padding": "[top=40,left=40,bottom=40,right=40]",
      "elk.layered.nodePlacement.strategy": "NETWORK_SIMPLEX",
      "elk.layered.crossingMinimization.strategy": "LAYER_SWEEP",
    },
    children: nodes.map((n) => ({
      id: n.id,
      width: NODE_WIDTH,
      height: NODE_HEIGHT,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      sources: [e.source],
      targets: [e.target],
    })),
  };

  const layout = await elk.layout(graph);
  const positions = new Map<string, { x: number; y: number }>();
  for (const child of layout.children ?? []) {
    if (child.x != null && child.y != null) {
      positions.set(child.id, { x: child.x, y: child.y });
    }
  }

  const layoutedNodes = nodes.map((node) => {
    const pos = positions.get(node.id);
    return {
      ...node,
      position: pos ?? { x: 0, y: 0 },
    };
  });

  return { nodes: layoutedNodes, edges };
}

function buildNodesAndEdges(
  mode: "all" | "asset",
  assetId: string | undefined,
  assets: AssetData[],
  flows: FlowData[]
): { nodes: AssetNode[]; edges: FlowEdge[] } {
  // Filter assets and flows based on mode
  let relevantAssetIds: Set<string>;
  let relevantFlows: FlowData[];

  if (mode === "asset" && assetId) {
    // Find flows connected to this asset (1-hop neighbors)
    relevantFlows = flows.filter(
      (f) => f.sourceAssetId === assetId || f.destinationAssetId === assetId
    );

    // Collect asset IDs from these flows
    relevantAssetIds = new Set<string>();
    relevantAssetIds.add(assetId);
    relevantFlows.forEach((f) => {
      relevantAssetIds.add(f.sourceAssetId);
      relevantAssetIds.add(f.destinationAssetId);
    });
  } else {
    // Show all assets that have at least one flow
    relevantFlows = flows;
    relevantAssetIds = new Set<string>();
    flows.forEach((f) => {
      relevantAssetIds.add(f.sourceAssetId);
      relevantAssetIds.add(f.destinationAssetId);
    });
  }

  // Build asset map for quick lookup
  const assetMap = new Map(assets.map((a) => [a.id, a]));

  // Calculate flow counts + per-asset category aggregation
  const incomingFlowCounts = new Map<string, number>();
  const outgoingFlowCounts = new Map<string, number>();
  const assetCategories = new Map<string, Set<string>>();

  const addCategories = (assetId: string, categories: string[]) => {
    let set = assetCategories.get(assetId);
    if (!set) {
      set = new Set<string>();
      assetCategories.set(assetId, set);
    }
    for (const c of categories) set.add(c);
  };

  relevantFlows.forEach((flow) => {
    incomingFlowCounts.set(
      flow.destinationAssetId,
      (incomingFlowCounts.get(flow.destinationAssetId) || 0) + 1
    );
    outgoingFlowCounts.set(
      flow.sourceAssetId,
      (outgoingFlowCounts.get(flow.sourceAssetId) || 0) + 1
    );
    addCategories(flow.sourceAssetId, flow.dataCategories);
    addCategories(flow.destinationAssetId, flow.dataCategories);
  });

  // Create nodes
  const nodes: AssetNode[] = [];
  for (const id of relevantAssetIds) {
    const asset = assetMap.get(id);
    if (!asset) continue;

    const categories = [...(assetCategories.get(asset.id) ?? [])];
    const peakSensitivity = classifyCategories(categories);

    nodes.push({
      id: asset.id,
      type: "assetNode",
      position: { x: 0, y: 0 }, // Will be set by layout
      data: {
        label: asset.name,
        asset,
        incomingFlows: incomingFlowCounts.get(asset.id) || 0,
        outgoingFlows: outgoingFlowCounts.get(asset.id) || 0,
        topCategories: categories.slice(0, 3),
        peakSensitivity,
        isHighlighted: false,
        isDimmed: false,
        isFocused: mode === "asset" && asset.id === assetId,
      },
    });
  }

  // Detect bidirectional pairs (A→B and B→A both exist)
  const pairKeys = new Set<string>();
  const bidirectionalKeys = new Set<string>();
  for (const flow of relevantFlows) {
    const fwd = `${flow.sourceAssetId}:${flow.destinationAssetId}`;
    const rev = `${flow.destinationAssetId}:${flow.sourceAssetId}`;
    if (pairKeys.has(rev)) {
      bidirectionalKeys.add(fwd);
      bidirectionalKeys.add(rev);
    }
    pairKeys.add(fwd);
  }

  // Create edges, marking return edges for bidirectional pairs
  const seenPairs = new Set<string>();
  const edges: FlowEdge[] = relevantFlows.map((flow) => {
    const key = `${flow.sourceAssetId}:${flow.destinationAssetId}`;
    const revKey = `${flow.destinationAssetId}:${flow.sourceAssetId}`;
    const isBidirectional = bidirectionalKeys.has(key);
    const isReturn = isBidirectional && seenPairs.has(revKey);
    seenPairs.add(key);

    const meta = flow.metadata as { autoGenerated?: boolean } | null | undefined;
    const isAutoGenerated = meta?.autoGenerated === true;

    return {
      id: flow.id,
      source: flow.sourceAssetId,
      target: flow.destinationAssetId,
      type: "flowEdge",
      animated: flow.isAutomated,
      data: {
        flow,
        label: flow.name,
        isBidirectional,
        isReturn,
        isAutoGenerated,
      },
    };
  });

  return { nodes, edges };
}

interface UseDataFlowGraphOptions {
  mode: "all" | "asset";
  assetId?: string;
  assets: AssetData[];
  flows: FlowData[];
}

export function useDataFlowGraph({
  mode,
  assetId,
  assets,
  flows,
}: UseDataFlowGraphOptions) {
  const [layoutedNodes, setLayoutedNodes] = useState<AssetNode[]>([]);
  const [layoutedEdges, setLayoutedEdges] = useState<FlowEdge[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Build initial nodes/edges without layout
  const { nodes: initialNodes, edges: initialEdges } = useMemo(
    () => buildNodesAndEdges(mode, assetId, assets, flows),
    [mode, assetId, assets, flows]
  );

  // Apply ELK layout (async)
  useEffect(() => {
    let cancelled = false;

    if (initialNodes.length === 0) {
      setLayoutedNodes([]);
      setLayoutedEdges([]);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    getLayoutedElements(initialNodes, initialEdges, "LR")
      .then(({ nodes: laidOutNodes, edges: laidOutEdges }) => {
        if (cancelled) return;
        setLayoutedNodes(laidOutNodes);
        setLayoutedEdges(laidOutEdges);
      })
      .catch((error) => {
        console.error("Failed to layout graph:", error);
        if (cancelled) return;
        // Fallback to a simple grid layout
        const gridNodes = initialNodes.map((node, i) => ({
          ...node,
          position: {
            x: (i % 4) * (NODE_WIDTH + 80),
            y: Math.floor(i / 4) * (NODE_HEIGHT + 80),
          },
        }));
        setLayoutedNodes(gridNodes);
        setLayoutedEdges(initialEdges);
      })
      .finally(() => {
        if (!cancelled) setIsLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [initialNodes, initialEdges]);

  return { nodes: layoutedNodes, edges: layoutedEdges, isLoading };
}
