/**
 * Pure, unit-testable transforms from raw Prisma rows into renderFlowGraphPng
 * inputs. Applies a production + participation filter by default and splits
 * into multi-page batches when node count exceeds a threshold.
 */
import type {
  PdfFlowAsset,
  PdfFlowEdge,
  PdfFlowCluster,
} from "../flow-graph-pdf";

export interface FlowAssetRow {
  id: string;
  name: string;
  type: string;
  isProduction: boolean;
}
export interface FlowEdgeRow {
  sourceAssetId: string;
  destinationAssetId: string;
  dataCategories: string[];
  frequency: string | null;
  isAutoGenerated: boolean;
}
export interface FlowActivityRow {
  id: string;
  name: string;
  assetIds: string[];
}

export interface FlowInputOptions {
  /** Filter to production assets only (default true). */
  productionOnly?: boolean;
  /** Max nodes per batch — above this the graph is split into multiple pages. */
  maxNodesPerBatch?: number;
}

export interface FlowBatch {
  /** Human-readable label for this batch's page heading. */
  label: string;
  assets: PdfFlowAsset[];
  edges: PdfFlowEdge[];
  clusters: PdfFlowCluster[];
}

export interface FlowInputResult {
  batches: FlowBatch[];
  /** Total assets before filtering. */
  originalAssetCount: number;
  /** Assets retained after filter. */
  filteredAssetCount: number;
  /** Number of assets dropped because they had no flows and no activity links. */
  orphansDropped: number;
}

export interface FlowInputLabels {
  unassigned: string;
  overview: string;
  moreSuffix: (count: number) => string;
}

export function buildFlowGraphInputs(
  assets: FlowAssetRow[],
  edges: FlowEdgeRow[],
  activities: FlowActivityRow[],
  options: FlowInputOptions = {},
  labels: FlowInputLabels = {
    unassigned: "Unassigned",
    overview: "Overview",
    moreSuffix: (count) => ` +${count} more`,
  }
): FlowInputResult {
  const productionOnly = options.productionOnly ?? true;
  const maxNodesPerBatch = options.maxNodesPerBatch ?? 60;

  // 1. Build participation index: which asset IDs touch ≥1 edge or activity
  const participates = new Set<string>();
  for (const e of edges) {
    participates.add(e.sourceAssetId);
    participates.add(e.destinationAssetId);
  }
  for (const a of activities) {
    for (const id of a.assetIds) participates.add(id);
  }

  // 2. Apply filter
  const kept = assets.filter((a) => {
    if (productionOnly && !a.isProduction) return false;
    return participates.has(a.id);
  });
  const keptIds = new Set(kept.map((a) => a.id));
  const orphansDropped = assets.length - kept.length;

  // 3. Drop edges that point to excluded assets
  const filteredEdges = edges.filter(
    (e) => keptIds.has(e.sourceAssetId) && keptIds.has(e.destinationAssetId)
  );

  // 4. Build the owner assignment: each asset assigned to the first (alpha)
  // activity that references it — mirrors ROPA cluster logic.
  const owner = new Map<string, string>();
  const sortedActivities = [...activities].sort((a, b) => a.name.localeCompare(b.name));
  for (const act of sortedActivities) {
    for (const id of act.assetIds) {
      if (keptIds.has(id) && !owner.has(id)) {
        owner.set(id, act.id);
      }
    }
  }

  // Unowned (no activity) → pseudo-cluster, label injected by caller
  const UNASSIGNED_ID = "__unassigned__";

  // 5. If all fits in one batch, return it.
  const assetNodes: PdfFlowAsset[] = kept.map((a) => ({
    id: a.id,
    name: a.name,
    type: a.type,
  }));
  const edgeNodes: PdfFlowEdge[] = filteredEdges.map((e) => ({
    sourceAssetId: e.sourceAssetId,
    destinationAssetId: e.destinationAssetId,
    label: [e.dataCategories[0], e.frequency].filter(Boolean).join(" · ") || undefined,
    isAutoGenerated: e.isAutoGenerated,
  }));

  const allClusters: PdfFlowCluster[] = [
    ...sortedActivities.map((a) => ({
      id: a.id,
      label: a.name,
      assetIds: a.assetIds.filter((id) => owner.get(id) === a.id),
    })),
    {
      id: UNASSIGNED_ID,
      label: labels.unassigned,
      assetIds: kept.filter((a) => !owner.has(a.id)).map((a) => a.id),
    },
  ].filter((c) => c.assetIds.length > 0);

  if (kept.length <= maxNodesPerBatch) {
    return {
      batches: [
        {
          label: labels.overview,
          assets: assetNodes,
          edges: edgeNodes,
          clusters: allClusters.length > 0 ? allClusters : [],
        },
      ],
      originalAssetCount: assets.length,
      filteredAssetCount: kept.length,
      orphansDropped,
    };
  }

  // 6. Batch clusters. Each batch fits ≤ maxNodesPerBatch clusters' worth.
  const batches: FlowBatch[] = [];
  let currentClusters: PdfFlowCluster[] = [];
  let currentAssetIds = new Set<string>();

  const flushBatch = () => {
    if (currentClusters.length === 0) return;
    const batchAssetIds = new Set<string>();
    for (const c of currentClusters) for (const id of c.assetIds) batchAssetIds.add(id);

    // Include assets referenced by edges inside this batch (source / dest)
    const batchEdges = edgeNodes.filter(
      (e) => batchAssetIds.has(e.sourceAssetId) && batchAssetIds.has(e.destinationAssetId)
    );

    const batchAssets = assetNodes.filter((a) => batchAssetIds.has(a.id));
    const labelList = currentClusters.map((c) => c.label).slice(0, 3);
    const suffix = currentClusters.length > 3 ? labels.moreSuffix(currentClusters.length - 3) : "";

    batches.push({
      label: `${labelList.join(" · ")}${suffix}`,
      assets: batchAssets,
      edges: batchEdges,
      clusters: currentClusters,
    });
    currentClusters = [];
    currentAssetIds = new Set<string>();
  };

  for (const cluster of allClusters) {
    if (
      currentAssetIds.size > 0 &&
      currentAssetIds.size + cluster.assetIds.length > maxNodesPerBatch
    ) {
      flushBatch();
    }
    currentClusters.push(cluster);
    for (const id of cluster.assetIds) currentAssetIds.add(id);
  }
  flushBatch();

  return {
    batches,
    originalAssetCount: assets.length,
    filteredAssetCount: kept.length,
    orphansDropped,
  };
}
