/**
 * Auto-Assessment Creation Service (Feature 5)
 *
 * Creates draft assessments automatically when high-risk vendors are imported
 * or when processing activities warrant it. Reused by Features 3, 5, and 7.
 */

import type { Prisma } from "@prisma/client";
import { AssessmentStatus, AssessmentType } from "@prisma/client";
import {
  checkAssessmentEntitlement,
  isPremiumAssessmentType,
} from "../services/licensing/entitlement";

interface AutoCreateParams {
  tx: Prisma.TransactionClient;
  organizationId: string;
  userId: string;
  processingActivityId?: string;
  vendorId?: string;
  vendorName?: string;
  assessmentType: AssessmentType;
  reason: string;
}

interface AutoCreateResult {
  created: boolean;
  assessmentId?: string;
  assessmentName?: string;
  skippedReason?: string;
}

/**
 * Create a draft assessment linked to a processing activity and/or vendor.
 * Checks entitlements for premium types; skips silently if not entitled.
 */
export async function createAssessmentFromActivity(
  params: AutoCreateParams
): Promise<AutoCreateResult> {
  const {
    tx,
    organizationId,
    userId,
    processingActivityId,
    vendorId,
    vendorName,
    assessmentType,
    reason,
  } = params;

  // Check entitlement for premium assessment types
  if (isPremiumAssessmentType(assessmentType)) {
    const entitlement = await checkAssessmentEntitlement(
      organizationId,
      assessmentType
    );
    if (!entitlement.entitled) {
      // Fall back to LIA if DPIA not entitled
      if (assessmentType === "DPIA") {
        return createAssessmentFromActivity({
          ...params,
          assessmentType: "LIA",
          reason: `${reason} (LIA fallback — DPIA requires premium license)`,
        });
      }
      return {
        created: false,
        skippedReason: `No ${assessmentType} entitlement`,
      };
    }
  }

  // Find the system template for this assessment type
  const template = await tx.assessmentTemplate.findFirst({
    where: {
      type: assessmentType,
      isActive: true,
      OR: [
        { isSystem: true },
        { organizationId },
      ],
    },
    orderBy: { isSystem: "desc" },
  });

  if (!template) {
    return {
      created: false,
      skippedReason: `No ${assessmentType} template available`,
    };
  }

  // Build assessment name
  const typeName = assessmentType === "LIA"
    ? "Legitimate Interests Assessment"
    : assessmentType === "DPIA"
      ? "Data Protection Impact Assessment"
      : `${assessmentType} Assessment`;
  const name = vendorName
    ? `${typeName} — ${vendorName}`
    : typeName;

  // Check for duplicate
  const existing = await tx.assessment.findFirst({
    where: {
      organizationId,
      name,
      status: { in: [AssessmentStatus.DRAFT, AssessmentStatus.IN_PROGRESS] },
    },
  });

  if (existing) {
    return {
      created: false,
      skippedReason: "Draft assessment already exists",
      assessmentId: existing.id,
    };
  }

  // Create the draft assessment
  const assessment = await tx.assessment.create({
    data: {
      organizationId,
      templateId: template.id,
      name,
      description: reason,
      processingActivityId,
      vendorId,
      status: AssessmentStatus.DRAFT,
      metadata: {
        autoGenerated: true,
        awaitingReview: true,
        reason,
      },
    },
  });

  // Audit log
  await tx.auditLog.create({
    data: {
      organizationId,
      userId,
      entityType: "Assessment",
      entityId: assessment.id,
      action: "AUTO_CREATE",
      changes: {
        type: assessmentType,
        vendorId,
        processingActivityId,
        reason,
      },
      metadata: { source: "auto-assessment" },
    },
  });

  return {
    created: true,
    assessmentId: assessment.id,
    assessmentName: name,
  };
}
